### ISSUE TITLE
Ordinamento in visualizzazione 

### ISSUE THREAD

**Issue by omnielong** [gmansillo/simple#100]
Ciao Giovanni, stiamo utilizzando il tuo modulo, ma avremmo necessità di risolvere un problema, trattandosi di una scuola le circolari inserite possono essere diverse, da utenti diversi in date diverse,
è possibile però dare un ordine nella visualizzazione ed evitare di trovare una circolare n. 210 prima di una circolare 199? e quindi pilotare eventualmente l'ordine di visualizzazione?

**Comment by gmansillo** [comment]
Ciao! Il componente utilizza lo stesso sistema di ordinamento degli articoli di Joomla!, per cui potrai ordinare i documenti per data, nome, dimensione, etc. ma anche definire un ordine personalizzato tramite drag and drop dei documenti nel backend. :arrow_up_small: :arrow_down_small:
