### ISSUE TITLE
Problemi visualizzazione lista documenti 

### ISSUE THREAD

**Issue by saverioV** [gmansillo/simple#102]
Ciao Giovanni, grazie per il tuo lavoro.
Ho un problema quando aggancio una lista di categoria di doc al menu. Non riesco a capire ma la lista esce senza agganciare nessun css. Dove prende il default e al limite come procedere per impostare uno stile che sia congruo al mio template (uso SP Page Builder)? 
Ancora tante grazie
Saverio

**Comment by gmansillo** [comment]
Ciao Saverio! 
Grazie per avermi contattato. Hai la possibilità di inviarmi un link alla pagina in questione?

**Comment by gmansillo** [comment]
Chiudo per assenza di informazioni.
La versione 5.2.2 include css specifico per il frontend.
