### ISSUE TITLE
Avviso via mail non funzionante.

### ISSUE THREAD

**Issue by Filotea** [gmansillo/simple#103]
Salve.
Da mesi non funziona più l'invio della mail autoatico ai destinatari al momento del caricamento di un documento nell'area personale.
Prima andava tutto bene, poi....niente da fare.
Versione Joomla 3.8.12
Versione PHP 7.2.8
Cosa fare per risolvere il problema?
Volevo anche fare donazione per lo sviluppo......

Rimango in attesa di informazioni in merito.
Grazie

**Comment by gmansillo** [comment]
Ciao @Filotea,
non ho abbastanza informazioni per risalire alla causa del problema. Che versione di Firedrive/Simple File Manager stai utilizzando? Prima di cosa andava tutto bene?

**Comment by Filotea** [comment]
La versione dovrebbe essere la 5.1.5 di febbraio 2018
L'anno scorso ho effettuato il download della versione Italiana e da quel momento in poi non partivano più le email.
Mi era stato consigliato di settare la versione php del sito ad una più aggiornata e così ho fatto ma....nulla da fare.
Dopo ho fatto aggioirnamento a quella ufficiale del vostro sio ma....nulla da fare. Continuano a non partire.
Mi sono pure accorto che, nonostante setto "Show MD5 sign" su "Nascondi", lo da comunque vedere nel lato frotend.
C'è qualcosa che non va per il verso giusto....
Attendo assistenza.
Grazie mille.

**Comment by gmansillo** [comment]
Per risailre al numero di versione dell'estensione puoi navigare in Extensions >  Manage > Manage e cercare **Simple File Manager** o **Firedrive**, in base alla versione installata. 
Per risalire al numero di versione di **Joomla** e di **PHP** puoi navigare in System > System Informations.
Queste informazioni mi sono utili per determinare la/le cause del problema

**Comment by gmansillo** [comment]
@Filotea, grazie alla tua segnalazione ho verificato che anche la versione in sviluppo soffre di questo problema ed ho provveduto a risolvere il bug dell'invio della notifica.
Rilascerò la fix il prima possibile, nel frattempo ho verificato che è possibile inviare le email manualmente selezionando la checkbox "Notify users" e premento il bottone "Save". 

Grazie ancora per la tua segnalazione.
G.

**Comment by gmansillo** [comment]
Fix disponibile a partire dalla versione 5.2.1

**Comment by Filotea** [comment]
Ho visto che la versione scaricabile di Simple File Manager è la 5.2.0 del 13 settembre 2018 e non la 5.2.1; quando sarà disponibile quella aggiornata con queste modifiche apportate?

(avrei voluto applicare io stesso i fix descritti ma sono per Firedrive...)

**Comment by gmansillo** [comment]
Firedrive 2.5.0 è Simplefilemanager 5.1.5: sono state rinominate le tabelle e le stringhe ma il codice è lo stesso. Puoi applicare manualmente la fix descritta nella commit 61807c3373c62e6d8da48699255ce3ee41261f1e

Il file interessato è admin/controllers/document.php

**Comment by Filotea** [comment]
Segnalo altresì che la checkbox "Notify users" spunta solo se modifico un documento precedentemente creato e non al momento del nuovo inserimento per cui si dovrebbe prima creare, poi cliccare su "Salva", poi spuntare la checkbox "Notify users" (perchè prima non spunta) e poi cliccare su "Salva e chiudi"

**Comment by gmansillo** [comment]
Quello che segnali è in realtà il comportamento atteso dalla checkbox: il seggerimento di utilizzarla per l'invio delle email è una soluzione non definitiva che ho proposto in attesa di trovare e correggere il bug. Ora che è disponbile la fix non è più necessario utilizzare la checkbox, la cui funzione primaria è quella di inviare nuovamente l'email di notifica nel caso di modifiche al documento, solleciti, ecc...

Grazie per la collaborazione,
G.

**Comment by Filotea** [comment]
Mi ritrovo documenti diversi....stringhe dieverse.....

Anzichè " admin/controllers/document.php" mi trovo 2 file: " admin/controllers/simplefilemanager.php" e " admin/controllers/simplefilemanagers.php"

Mi sa che si saranno accavallate versioni diverse nel tempo ed ora è tutto incasinato.

Ricordo che a seguito di 2 aggiornamenti tempo addietro, si sono scollegati tutti i documenti caricati per cui, ber ben 2 volte, ho docuto ricollegarli tutti uno ad uno!
A fronte di questo oggi temo pure ad aggiornare il componente....

HELP PLEASE!

**Comment by gmansillo** [comment]
Comprendo e sono molto dispiaciuto per l'accaduto. La soddisfazione degli utenti è importante per me per cui cercherò di elencare passo passo le modifiche da fare per risolvere il problema dell'invio automatico delle notifiche nella versione che utilizzi attualmente, senza dover ricorrere agli aggiornamenti:
1. Copiare il file administrator/com_simplefilemanager/controllers/simplefilemanager.php in administrator/com_simplefilemanager/controllers/simplefilemanager.php.bak in modo da avere una copia di backup
2. Aprire in modifica il file administrator/com_simplefilemanager/controllers/simplefilemanager.php e sistituire l'intera funzione postSaveHook con la seguente:
```
protected function postSaveHook(JModelLegacy $model, $validData = [])
{
	$item  = $model->getItem();
	$isNew = $this->form["id"] == 0;
	$db    = JFactory::getDbo();
// Update document user visibility settings
	$query = $db->getQuery(true);
	$query->delete($db->quoteName('#__simplefilemanager_user_documents'));
	$query->where($db->quoteName('document_id') . ' = ' . $item->id);
	$db->setQuery($query);
	$db->execute();
	if (isset($this->form['reserved_user']))
	{
		foreach ($this->form['reserved_user'] as $u)
		{
			$rel              = new stdClass();
			$rel->user_id     = $u;
			$rel->document_id = $item->id;
			JFactory::getDbo()->insertObject('#__simplefilemanager_user_documents', $rel);
		}
	}
// Update document group visibility settings
	$query = $db->getQuery(true);
	$query->delete($db->quoteName('#__simplefilemanager_group_documents'));
	$query->where($db->quoteName('document_id') . ' = ' . $item->id);
	$db->setQuery($query);
	$db->execute();
	if (isset($this->form['reserved_group']))
	{
		foreach ($this->form['reserved_group'] as $g)
		{
			$rel              = new stdClass();
			$rel->group_id    = $g;
			$rel->document_id = $item->id;
			JFactory::getDbo()->insertObject('#__simplefilemanager_group_documents', $rel);
		}
	}
// Send notify email
	if (($isNew && $this->params->get('sendmail', 0)) || isset($this->form["fl_send_mail"]))
	{
		$recipients = array();
// Check requisites for email sending
		if ($this->form["state"] != 1)
		{
			JFactory::getApplication()->enqueueMessage(JText::_('COM_SIMPLEFILEMANAGER_SENDMAIL_UNPUBLISHED_DOCUMENT_ERROR'), 'warning');
		}
		elseif ($this->form["visibility"] == 3)
		{
// Get recipients email from db
			$db    = JFactory::getDbo();
			$query = $db->getQuery(true);
			$query->select('user_id')
				->from('#__simplefilemanager_user_documents')
				->where('document_id = ' . $item->id);
			$db->setQuery($query);
			$recipients = $db->loadColumn();
		}
		else if ($this->form["visibility"] == 4)
		{
			$db    = JFactory::getDbo();
			$query = $db->getQuery(true);
			$query->select('group_id')
				->from('#__simplefilemanager_group_documents')
				->where('document_id = ' . $item->id);
			$db->setQuery($query);
			$group_ids = $db->loadColumn();
			foreach ($group_ids as $g_id)
			{
				$recipients = array_merge($recipients, JAccess::getUsersByGroup($g_id));
			}
// Remove duplicates
			$recipients = array_unique($recipients, SORT_REGULAR);
		}
		elseif (isset($this->form["fl_send_mail"]))
		{
// Alert only if send mail is forced
			JFactory::getApplication()->enqueueMessage(JText::_('COM_SIMPLEFILEMANAGER_SENDMAIL_UNSUPPORTED_VISIBILITY_ERROR'), 'warning');
		}
		if (!empty($recipients))
		{
			$config = JFactory::getConfig();
			$sender = [$config->get('mailfrom'), $config->get('fromname')];
			$author = JFactory::getUser((int) $item->created_by);
			foreach ($recipients as $recipient)
			{
				$user = JFactory::getUser((int) $recipient);
// Message subject
				$subject = JText::_('COM_SIMPLEFILEMANAGER_EMAIL_SUBJ');
// Message body
				$body = JText::_('COM_SIMPLEFILEMANAGER_EMAIL_BODY');
				$body = str_replace('{user_fullname}', $user->name, $body);
				$body = str_replace('{document_title}', $item->title, $body);
				$body = str_replace('{author_name}', $$author->name, $body);
				$body = str_replace('{site_url}', JUri::base(), $body);
// Send email
				$mailer = JFactory::getMailer();
				$mailer->setSender($sender);
				$mailer->addRecipient($user->email);
				$mailer->setSubject($subject);
				$mailer->isHTML(true);
				$mailer->Encoding = 'base64';
				$mailer->setBody($body);
				$send = $mailer->Send();
				if (!$send)
				{
					JFactory::getApplication()->enqueueMessage(JText::_('JERROR') . ": " . $send->__toString(), 'error');
				}
			}
		}

		return true;
	}
	parent::postSaveHook($model, $validData);
}

```
3. Salvare le modifiche

Questo codice funziona esclusivamente per Simplefilemanager (quella in uso) e non per la versione rinominata in Firedrive.

**Comment by Filotea** [comment]
Perfetto, adesso funziona!!
La mail arriva in inglese, nonostante settata in italiano, ma già va meglio. Testato ed adesso parte in automatico.
Per altre limature e suggerimenti posso creare altri post?

**Comment by gmansillo** [comment]
Si grazie

**Comment by Filotea** [comment]
Segnalo che il tag {site_url} riporta a "http://nomesito/administrator} e non a "http://nomesito" soltanto

E' possibile avere una lista di questi tag (se si chiamano così) per personalizzare i messaggi?

**Comment by gmansillo** [comment]
Sempre nello stesso file, stessa funzione, puoi sostituire 
```$body = str_replace('{site_url}', JUri::base(), $body);``` 
con 
```$body = str_replace('{site_url}', JUri::root(), $body);```

Al momento i segnaposto sono solo 4:
- {user_fullname} è il nome completo dell'utente
- {document_title} è il titolo del documento
- {author_name} è il nome completo dell'autore del documento
- {site_url} (dopo la modifica) è la url della root del sito
