### ISSUE TITLE
Errore data al salvataggio

### ISSUE THREAD

**Issue by maxsoftware69** [gmansillo/simple#104]
Buongiorno e complimenti per il componente..davvero facile da utilizzare. 
Al salvataggio ricevo però il seguente messaggio:   
Attenzione    Campo non valido: Created Date  Campo non valido: Data modifica
Ho verificato l'oraro di PHP e di MYSQL del server e sono corretti, ma il documento caricato si salva con 2 ore di anticipo. Esempio: se sono le 12.01 quando carico il documento l'orario di creazione e modifica nella tabella corrisponde a 10.01..2 ore di differenza.
Ho visto che già qualcuno aveva lo stesso problema. Ho la versione 5.2.0
spero sia un problema da poco

**Comment by gmansillo** [comment]
Ciao @maxsoftware69,
grazie per l'apprezzamento. C'è molto lavoro da fare sulle date e grazie alla tua segnalazione ho trovato un altro bug. Provvederò quanto prima a risolverlo, sperando di trovare rapidamente la causa!

**Comment by gmansillo** [comment]
Ciao @maxsoftware69,
ho fatto delle modifiche sul codice, sembrerebbe che l'errore non si presenta più.
Gli orari salvati sul database restano comunque relativi all'ora di Greenwich, sarà Joomla a convertire l'orario in base al fuso orario dell'utente (di default Joomla! prende il fuso orario delle impostazioni globali).

Appena possibile rilascio pacchetto aggiornato.

Grazie ancora per la segnalazione e per la tua pazienza! :wink: 

G.

**Comment by gmansillo** [comment]
Fix disponibile a partire dalla versione 5.2.1
