### ISSUE TITLE
500 error, file not found

### ISSUE THREAD

**Issue by Lacis** [gmansillo/simple#106]
Ciao Giovanni!
Thanks for component. :)

Installed firedrive 5.2.2. Added two docs. In category view pushing download shows 500 exception 'Exception'
**
500 exception 'Exception' with message 'Document not found.' in /home/user/public_html/page_directory/components/com_firedrive/models/document.php:115 Stack trace: #0 /home/user/public_html/page_directory/libraries/src/MVC/View/HtmlView.php(423): FiredriveModelDocument->getItem() #1 /home/user/public_html/page_directory/components/com_firedrive/views/document/view.html.php(74): Joomla\CMS\MVC\View\HtmlView->get('Item') #2 /home/user/public_html/page_directory/libraries/src/MVC/Controller/BaseController.php(672): FiredriveViewDocument->display() #3 /home/user/public_html/page_directory/components/com_firedrive/controller.php(62): Joomla\CMS\MVC\Controller\BaseController->display(false, Array) #4 /home/user/public_html/page_directory/libraries/src/MVC/Controller/BaseController.php(710): FiredriveController->display() #5 /home/user/public_html/page_directory/components/com_firedrive/firedrive.php(33): Joomla\CMS\MVC\Controller\BaseController->execute(NULL) #6 /home/user/public_html/page_directory/libraries/src/Component/ComponentHelper.php(382): require_once('/home/socialasr...') #7 /home/user/public_html/page_directory/libraries/src/Component/ComponentHelper.php(357): Joomla\CMS\Component\ComponentHelper::executeComponent('/home/socialasr...') #8 /home/user/public_html/page_directory/libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent('com_firedrive') #9 /home/user/public_html/page_directory/libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch() #10 /home/user/public_html/page_directory/libraries/src/Application/CMSApplication.php(195): Joomla\CMS\Application\SiteApplication->doExecute() #11 /home/user/public_html/page_directory/index.php(49): Joomla\CMS\Application\CMSApplication->execute() #12 {main}
***

Open Doc view and push download, opening blank page, nothing more. 

Sinclery.

**Comment by gmansillo** [comment]
Hi @Lacis,
thank you for alerting me! The issue is in components/com_firedrive/views/category/tmpl/default_items.php at line 200. That line should be:
`<?php echo '<a href="', JRoute::_('index.php?option=com_firedrive&amp;view=document&amp;id=' . $item->id . '&amp;format=raw'), '" class="btn btn-default">', JText::_('COM_FIREDRIVE_DOWNLOAD_BUTTON'), '</a>'; ?>`
Please make this fix manually otherwise I'm going to release an update as soon as possible!

Thank you very much!

**Comment by gmansillo** [comment]
Ok, just released Firedrive 5.2.3 that fixes the bug. Thank you again @Lacis !

**Comment by Lacis** [comment]
Thanks.
After update No more this error.
Shows other one: Joomla\CMS\Document\RawDocument::addHeadLink(): Class 'finfo' not found
I will look maybe somebody already wrote about this.

**Comment by gmansillo** [comment]
Hi @Lacis, this error often means that minimum requirements are not met. 
finfo is a php class available since PHP 5.3 (but 5.4 is required for running firedrive!)

hope it helps

**Comment by Lacis** [comment]
Thanks.

Great. I have 2 page old, new. Switched 7 PHP, added finfo. Works.
But using Safari (version 12.), pdfs files are downloaded as.html

P.S Could be Safari problem. Can you test?

**Comment by gmansillo** [comment]
Thank you or the feedback. Unfortunately I can't test Safari but if you want you can try to add this code:
```
			exit;
```
at line 77 of components/com_firedrive/views/document/view.raw.php. If it solves the problem, I'll add it to the source code.

**Comment by Lacis** [comment]
Thanks.
Added.
echo JFile::read($item->file_name);
		exit; }
		catch (Exception $e)

on Safari the same, downloaded file with .html suffix. 
Chrome ok. 
Other didn't tested

**Comment by gmansillo** [comment]
Please, try to replace line 57 of the same file with the following one:
`$f_mime      = $f_info->file($item->file_name, FILEINFO_MIME);`

Does it solve the problem?

**Comment by Lacis** [comment]
Hi.

Change. 
Safari still the same. Chrome ok.

**Comment by gmansillo** [comment]
I just tested it on Safari 5.1 for Windows 7 via this online service: https://www.browserling.com/browse/win/7/safari/5.1/https%3A%2F%2Fwww.firedrive.eu%2Fdemo%2F 
but there doesn't seem to be any error in downloading pdf files. It seems that your server isn't able to recognize the right mime type for you pdfs and then joomla sets the default type "text/html".

This can only be fixed avoiding to set the mime type, then commenting the following lines in the same file (_components/com_firedrive/views/document/view.raw.php_):
```
			$doc->setMimeEncoding($f_mime, true);
			$app->setHeader('Content-Type', $f_mime, true);
```

**Comment by gmansillo** [comment]
Again, i tested it locally on lubuntu 18.04 via wine and safari 5.1.7 for windows and there doesn't seem to be any error:

![2018-10-17-220933_1366x768_scrot](https://user-images.githubusercontent.com/11967003/47113540-99db2b80-d259-11e8-9ba2-88ff77dcc592.png)

**Comment by Lacis** [comment]
Again Thanks for communication :)

I don't write, I use Safari and chrome on MAC, and page on hosting not local web. I'm not sure about hosting server, could be ok. 
I will test on windows chrome, Firefox, safari, and write a comment.

**Comment by gmansillo** [comment]
Did you try to comment those two lines? This way safari should try to determine file type by itself and should not add the html extension

**Comment by Lacis** [comment]
How do it correct, commenting
$doc->setMimeEncoding($f_mime, true);
			$app->setHeader('Content-Type', $f_mime, true);

**Comment by gmansillo** [comment]
Yes, you can comment those two lines in this way:
```
// $doc->setMimeEncoding($f_mime, true);
// $app->setHeader('Content-Type', $f_mime, true);
```
or you can replace them with:
```
$doc->setMimeEncoding("application/octet-stream", true);
$app->setHeader('Content-Type', "application/octet-stream" true);
```

**Comment by Lacis** [comment]
ok.

By this way
$doc->setMimeEncoding("application/octet-stream", true);
$app->setHeader('Content-Type', "application/octet-stream" true);
shows
Error: Call to undefined method Joomla\CMS\Document\RawDocument::addHeadLink(): syntax error, unexpected 'true' (T_STRING), expecting ',' or ')'

But this
// $doc->setMimeEncoding($f_mime, true);
// $app->setHeader('Content-Type', $f_mime, true);

On Mac OS, 
Safari, the same, downloaded file with .html suffix. 
other, FireFox, Opera OK!

**Comment by gmansillo** [comment]
By chance, did you enable this option in Joomla! control panel?

![Add suffix to url](https://camo.githubusercontent.com/3869bdbd952a06f428a301a6995765410eef0df9/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f33383366386534323366613665653839323430393632353339653062643063312e706e67)

**Comment by Lacis** [comment]
Ok.
I did not. Now switch on. But, the same :( 
Seems only on Safari in Mac OS X.

I could'n test on Windows Safari

**Comment by gmansillo** [comment]
If you paste the download url in http://www.redirect-checker.org/index.php (right click on download button and select "copy link location") what do you get?

I'm interested in the "HTTP Headers" part, the one that looks like the following:

<p>&gt;&gt;&gt;  http://www.firedrive.eu/get/update/<br></p><p>&gt; --------------------------------------------<br>&gt; 200 OK<br>&gt; --------------------------------------------<br></p><table><tbody><tr><td><strong>Status:</strong></td><td>200 OK</td></tr><tr><td><strong>Code:</strong></td><td>200</td></tr><tr><td><strong>Date:</strong></td><td> Tue, 23 Oct 2018 21:59:42 GMT</td></tr><tr><td><strong>Server:</strong></td><td> Apache</td></tr><tr><td><strong>Vary:</strong></td><td> Accept-Encoding</td></tr><tr><td><strong>Connection:</strong></td><td> close</td></tr><tr><td><strong>Content-Type:</strong></td><td> text/xml;charset=UTF-8</td></tr></tbody></table><p><br></p><p><br></p>		
			</div>

**Comment by Lacis** [comment]
Done.

Status: | 200 OK
-- | --
Code: | 200
Server: | nginx
Date: | Wed, 24 Oct 2018 05:02:26 GMT
Content-Type: | text/html; charset=utf-8
Content-Length: | 108542
Connection: | close
X-Powered-By: | PHP/7.2.11
Content-Disposition: | attachment; filename="filenameabc.pdf";
Content-Transfer-Encoding: | binary
Expires: | Wed, 17 Aug 2005 00:00:00 GMT
Cache-Control: | no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: | no-cache
Set-Cookie: | 8f62c45b9d48f316d895682a9ed1f260=0a6e7af4299a62016a85f4e52a5fd117; path=/; secure; HttpOnly
Last-Modified: | Wed, 24 Oct 2018 05:02:26 GMT
