### ISSUE TITLE
sort documents by descending date by default

### ISSUE THREAD

**Issue by gps70** [gmansillo/simple#108]
Hi, thanks for your great work.
I would like to know if it is possible to order documents by default in order to have the last one always inserted at the top.
Thanks for the help

**Comment by gmansillo** [comment]
Hi @gps70,
of course you can set a default ordering via **Firedrive > Documents > Options > Category > Default ordering**.
Hope it helps.

Sincerely,
Giovanni

**Comment by gps70** [comment]
Ciao Giovanni ho fatto come hai scritto Ma gli articoli vengono comunque
pubblicati mettendo al primo posto il più vecchio e non l'ultimo inserito

Il Lun 22 Ott 2018, 01:06 Giovanni Mansillo <notifications@github.com> ha
scritto:

**Comment by gmansillo** [comment]
This is a bug to be fixed. Thanks for reporting

**Comment by ArnoutVos** [comment]
In no way a fix, but if you need descending ordering, just modify line 351 of models/category.php from:

`		$query->order($db->escape($this->getState('list.ordering', 'a.ordering')) . ' ' . $db->escape($this->getState('list.direction', 'ASC')));`

to:

`		$query->order($db->escape($this->getState('list.ordering', 'a.ordering')) . ' DESC');`

**Comment by gmansillo** [comment]
Bug fixed. Correction in next update.
Thank you for reporting it
