### ISSUE TITLE
description bug

### ISSUE THREAD

**Issue by alemastudio** [gmansillo/simple#11]
description field not save html formatting
nel campo descrizione non è possibile salvare la formattazione

**Comment by gmansillo** [comment]
That is a very good point! Thank you Alemastudio, I'll fix this bug in the next update

**Comment by gmansillo** [comment]
Issue fixed since v5.0.8.
Thank you alemanstudio

**Comment by alemastudio** [comment]
WHEN will be released this version ?
I can pay you right away if you make me change

**Comment by gmansillo** [comment]
Today, I only need the time to create the package and to update references.
v5.0.8 also introduces other fixes.

2016-05-06 10:11 GMT+02:00 alemastudio <notifications@github.com>:

**Comment by alemastudio** [comment]
thank you

**Comment by alemastudio** [comment]
buonasera, scusami se ti disturbo e insisto, ma è molto importante per me.
riesci a pubblicare l'aggiornamento entro stasera?
ti mando subito un pagamento paypal se puoi
grazie e scusa

2016-05-06 10:34 GMT+02:00 Giovanni <notifications@github.com>:

**Comment by gmansillo** [comment]
5.0.8 is now available from the GitHub repo: https://github.com/gmansillo/simplefilemanager/releases

**Comment by alemastudio** [comment]
Grazie mille
Il 07/mag/2016 12:43 AM, "Giovanni" notifications@github.com ha scritto:
