### ISSUE TITLE
Exporting Simple documents and categories to Firedrive

### ISSUE THREAD

**Issue by maja1063** [gmansillo/simple#110]
How do I export Simple documents and categories to Firedrive?

**Comment by gmansillo** [comment]
Hi @maja1063,
thanks for contacting. Which version of Simple File Manager are you using?

**Comment by maja1063** [comment]
Hi Govianni,

Thanks for your quick answer.

I actually use 2 different versions: 5.1.2 and 5.1.5.

Best Regards,
Marek
  ----- Original Message -----

**Comment by maja1063** [comment]
Hi Govianni, Thanks for your quick answer. I actually use 2 different versions: 5.1.2 and 5.1.5. Best Regards, Marek

**Comment by gmansillo** [comment]
Marek, sorry for delay in reply but unfortunately this morning, after answered to your first post, I broken my computer so for the moment i'm not able to test anything :(
Simple 5.1.5 database schema is identical to the Firedrive one so you can simply rename all #_simplefilemanager_foo tables to #_firedrive_foo for moving logical items from simple to firedrive.
Next step is to move the "uploads" folder from administrator/components/com_simplefilemanager/ to administrator/components/com_firedrive/
At this point you need only to take two last steps: first one is to rename all logical paths in file_name column in #_simplefilemanager table (when I'll get a working pc I'll send you the right script, if you need help with it); second and last one is to move simplefilemanager categories to firedrive in the #_categories table. It's a simple operation (you have only to replace simplefilemanager with Firedrive in the "extension" column). I'll send you also this script if you need it.

**Comment by maja1063** [comment]
Hello Giovanni,

Can I do the same with version 5.1.2 as for version 5.1.5 ?
In fact, with this version I have a lot of documents and categories stored.

Also, please send the the script that you are mentioning below.

Best Regards,
Marek 


  ----- Original Message -----

**Comment by gmansillo** [comment]
For 5.1.5 you should execute the following command on the database:
```
DROP TABLE jos_firedrive;
ALTER TABLE jos_simplefilemanager RENAME TO jos_firedrive; 
DROP TABLE jos_firedrive_download_tracking;
ALTER TABLE jos_simplefilemanager_download_tracking RENAME TO jos_firedrive_download_tracking
DROP TABLE jos_firedrive_group_documents;
ALTER TABLE jos_simplefilemanager_group_documents RENAME TO jos_firedrive_group_documents;
DROP TABLE jos_firedrive_user_documents;
ALTER TABLE jos_simplefilemanager_user_documents RENAME TO jos_firedrive_user_documents;
```
for renaming tables. NB: You have to replace jos_ with the correct table prefix.

Then execute
```
UPDATE jos_firedrive SET  file_name = REPLACE(file_name, 'com_simplefilemanager', 'com_firedrive');
```
for fixing file paths

then
```
UPDATE jos_categories SET  extension = 'com_firedrive' WHERE extension = 'com_simplefilemanager';
```
for moving categories from simple to firedrive.

**Comment by gmansillo** [comment]
Closed for lack of response
