### ISSUE TITLE
area download

### ISSUE THREAD

**Issue by yay076** [gmansillo/simple#111]
Buongiorno,
ho creato una voce di menu "download"  di tipo "elenco documenti" e ho impostato l'accesso su "registered" poiché voglio che i file siamo scaricabili solo da utenti registrati.
Nel sito ho inserito un pulsante CTA con link alla voce di menu "download" che visualizza i documenti scaricabili se l'utente è già loggato, mentre se non loggato mostra il form di accesso di joomla.
Nella seconda ipotesi però viene si mostrato il modulo di login ma anche altri moduli assegnati ad altre pagine del sito, come posso risolvere?

Grazie

**Comment by gmansillo** [comment]
Ciao,
la pagina di login è gestita dal componente com_users, credo che tu debba creare una voce di menu di quel tipo ed assegnare a questa solo i moduli che vuoi mostrare in quel contesto.

**Comment by yay076** [comment]
Ciao,
ma  è disponibile anche il modulo Firedrive o solo il componente?
Grazie

**Comment by gmansillo** [comment]
Firedrive è un componente, al momento non ha moduli.
