### ISSUE TITLE
Problem downloading file

### ISSUE THREAD

**Issue by crimauri** [gmansillo/simple#112]
Hi Giovanni, I have a problem downloading files. When I download them they are corrupted and cannot view them but when I check them from the administrator site I open them with no problem.

Can you help me to solve this issue?

Thank you

**Comment by gmansillo** [comment]
Hi @crimauri ,
can you send me more informations about the production environment? I.e. os, http server (apache, nginx, etc), php version, joomla version?

**Comment by mercomtw** [comment]
Same Problem here, what can i do?
It's a local Server whith WAMP

**Comment by mercomtw** [comment]
Da hier vom Entwickler keine Antwort kommt, gehe ich davon aus mir eine andere Komponente zu suchen. 
Thats why you are here, steht auf der Webseite. Das glaube ich nicht! Schlechter Support geht genauso.

**Comment by ghost** [comment]
Ho lo stesso problema con joomla 3.9.1, apache 2.4.37 e php 7.2.12 in locale. Mi dice "Non è possibile trovare la pagina richiesta" cliccando sul pulsante download. 
I have the same problem with joomla 3.9.1, apache 2.4.37 and php 7.2.12 in local test. He tells me "The requested page can not be found" by clicking on the download button.

**Comment by mercomtw** [comment]
Wir nutzen jetzt jdmfree. Viel einfacher und logischer zu nutzen und ohne Fehler.

**Comment by ghost** [comment]
Pity, thank you.

**Comment by gmansillo** [comment]
Thank you for reporting the issue. I'm trying the @CristianoSias environment for testing it. In fact no one else (@mercomtw, @crimauri) gave me further informations about the server, etc. so i can't do anything for them. 
I'll write you as soon as i have any update.

**Comment by gmansillo** [comment]
Hi, please try to download the last committed code (bef4dac43180d1648e787574239cbce739c76352) from: [https://github.com/gmansillo/Firedrive/archive/master.zip](https://github.com/gmansillo/Firedrive/archive/master.zip) 
It seems to work fine with your test environment. Let me know!

**Comment by ArnoutVos** [comment]
Possible cause of this issue is having PHP warnings enabled. If you view the corrupted download file (only in the front-end) you can see the warnings it injects before the file header (in this case a PDF):
```
<br />
<b>Warning</b>:  Use of undefined constant file_name - assumed 'file_name' (this will throw an Error in a future version of PHP) in <b>/var/www/html/joomla/components/com_firedrive/views/document/view.raw.php</b> on line <b>57</b><br />
<br />
<b>Warning</b>:  finfo::file(file_name): failed to open stream: No such file or directory in <b>/var/www/html/joomla/components/com_firedrive/views/document/view.raw.php</b> on line <b>57</b><br />
%PDF-1.5
```
Solution is to switch off warnings in PHP configuration (which is the default, and Joomla will also warn you about this). But for dev/test environments it is OK to turn them on.

**Comment by gmansillo** [comment]
Fixed in 5.2.4. 
Thank you for notifying it.

**Comment by charlieIT** [comment]
Having this issue right now, every file downloaded from frontend ends up corrupted upon opening

**Comment by gmansillo** [comment]
Hi @charlieIT,
which version of Firedrive are you using?
