### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by nebulamedia** [gmansillo/simple#114]
When trying to upload any file on test site I have created I get this error. Simple File Manager worked fine on this same test site.
Call to a member function get() on null...
.../components/com_firedrive/controllers/documentform.php:117

Thanks for any assistance on this.

**Comment by gmansillo** [comment]
Hi,
I can't recreate the issue. Can you give me more informations about the step you follow and about your environment (i.e. Server, Joomla! and Firedrive version)?

![immagine](https://user-images.githubusercontent.com/11967003/50665937-e578b800-0fb2-11e9-9b7e-fffa301d0cdd.jpg)

**Comment by nebulamedia** [comment]
This is a clean install of Joomla 3.9.1, only components are firedrive and jce. Apache 2.2, php 7.2, MySQL 5.6+, firedrive version 5.2.3 (I think - whatever is latest).

Using protostar theme, this is just for test. Also tried beez3 with same result.

Thanks for any help. 

Jason

**Comment by ghost** [comment]
Same issue for me. Created a menu item type "firedrive document upload". 

Moved to site, logged in with role Author, used newly created menu item for document. 
Added a title, selected file, added description and submited
--> Error 500 Call to a member function get() on null

=============
System Information
=============
php: Linux s075.cyon.net 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.22-log-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.1.24
server: LiteSpeed
sapi_name: litespeed
version: Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

Regards
Mathias

**Comment by gmansillo** [comment]
Thank you @pensulo,
then it's a frontend issue and not a backend one. Anyway, I'm going to verify it.

**Comment by nebulamedia** [comment]
Yes, sorry I did not specify this. I was only thinking in the context of what I was trying. I was able to successfully upload from backend just not from front. Thanks again for any help.

**Comment by nebulamedia** [comment]
is there any resolution to this issue yet? I believe this issue began with the Joomla 3.9.1 update and also affects 3.9.2.

**Comment by nebulamedia** [comment]
ok, so through some additional trial and error with older installations of joomla, simple file manager, firedrive, and a number of configurations, I have been able to resolve the issue. The issue related to the joomla user permissions. I had created a new user group and access level. Even though I had gone through under options and given adequate permissions, this continued to fail until i raised the parent level to at least Manager. That resolved the issue.

**Comment by camillocam** [comment]
Hello,  I've this problem. I try upload file from FRONT-END and when i save  there is error "0 - Call to a member function get() on null".
The error is  

> [Fri Feb 01 12:29:52.652230 2019] [php7:notice] [pid 54668] [client ::1:56028] PHP   9. FiredriveControllerDocumentForm->save() /XXX/libraries/src/MVC/Controller/BaseController.php:710, referer: http://localhost/XXX/modulo/moduli-famiglie-roma.html
I change user from Editor to Manager   but the I've error

If i upload file from Back-end with administrator i dont' have problem.

**Comment by charlieIT** [comment]
Found a potential solution to this issue by adding 
`$params       = JComponentHelper::getParams('com_firedrive');` inside function save() of file controllers\documentform.php and editing the defaullt template view of documentform by removing this condition
`<?php if ($this->item->params->get('default_category', "") == ""): ?>
				<?php echo $this->form->renderField('catid'); ?>
			<?php endif; ?>`
and forcing the category (catid) dropdown chooser to always display itself
`<?php echo $this->form->renderField('catid'); ?>`

I also tried using php version 5.6 in my apache server, instead of 7.2, but the original error still remained. Although with php 5.6 I was able to get further information about the error, that eventually led me to make the above changes.

This solution requires the existence of categories, created via backend, and will force the user to select the prefered category for the file.
I tested the download features after these changes and both frontend and backend downloads are working for me.

**Comment by camillocam** [comment]
Where is this code `<?php if ($this->item->params->get('default_category', "") == ""): ?> <?php echo $this->form->renderField('catid'); ?> <?php endif; ?> `, In default template of joomla ?

**Comment by charlieIT** [comment]
@camillo860 code for that specific part was/is in file default.php in directory: /com_firedrive/views/documentform/tmpl/

**Comment by gmansillo** [comment]
I just edited the code. Please check if 5.2.4 (soon available) still presents the issue.
