### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by ghost** [gmansillo/simple#115]
I created german translations for firedrive, feel free to integrate them. 

Additional, made some corrections on the english translations. Everything attached.
[language.zip](https://github.com/gmansillo/Firedrive/files/2729356/language.zip)

**Comment by charlieIT** [comment]
thanks :D it also helped with frontend translations

**Comment by gmansillo** [comment]
Thank you @pensulo! I would like contributors to publish translations on Joomla! local community website since I'm not able to keep them updated.
