### ISSUE TITLE
View not found [name, type, prefix]: import, html, firedriveView

### ISSUE THREAD

**Issue by imperimus** [gmansillo/simple#117]
When I click import I get the following error:

View not found [name, type, prefix]: import, html, firedriveView

Joomla! Version | Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT
-- | --
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by gmansillo** [comment]
Hi, the import view is in a test stage, you shouldn't see the button/menu item linking to it. Wich version of Firedrive are you using?

**Comment by ghardin26** [comment]
I also have this problem. Version is 5.2.3 as available on your site.  If it has bugs you should take it down.  I wiull use 5.2.2 until you fix it

**Comment by ghardin26** [comment]
Also.  The import button does not work on 5.2.2 either.  And the Update url in Joomla for your application does not work and gives an error.
The Blue Get It Now button on your website is the same url as the update site url and also does nothing.
Better to not be in a hurry and get your app working properly than to publish and have lots of bugs.  Not a good first impression!

**Comment by gmansillo** [comment]
Thank you for reporting these issues.
I removed the import menu item from backend in firedrive component and I fixed the download button on firedrive.eu: it was a server misconfiguration.
