### ISSUE TITLE
Change path destination file

### ISSUE THREAD

**Issue by vonbalk** [gmansillo/simple#118]
Hello, thanks for the excellent work.
i wanted to ask you, is it possible to change the destination path of the files uploaded ?
I can't  find the option.
Then, when I load a file from the front end it returns "0 Call to undefined method FiredriveController::save()"
I use joomla 3.9.1 and php 7.1

**Comment by gmansillo** [comment]
Hi, I wasn't able to reproduce the issue. Can you give me more information about your environment?

**Comment by gmansillo** [comment]
Unfortunately, it isn't possible to change the destination path of the files uploaded
