### ISSUE TITLE
Deafult Category

### ISSUE THREAD

**Issue by cgiardiniere** [gmansillo/simple#120]
Buongiorno. Joomla 3.9.2 e Firedrive 5.2.3.

In Global Configuration nelle opzioni di Firedrive non ho impostato alcuna Default Category. 
Ho creato due distinte voci di menù, accessibili da due diverse tipologie di utente che dovranno caricare dei file in due categorie distinte. Se non imposto nessuna categoria di default a livello di voce di menù, funziona tutto correttamente, ma quando imposto una default category, nella pagina di upload non appare più il campo "Categoria" - e questo in realtà ha senso - però poi succede che  quando provo ad uploadare il file mi appare una pagina vuota e l'upload non avviene. 

C'è modo di risolvere l'anomalia? Grazie mille. Paolo.

**Comment by gmansillo** [comment]
Grazie Paolo per la segnalazione, verifico quanto prima e fixo. 

Edit: si tratta di upload da front-end o da backend?

**Comment by cgiardiniere** [comment]
Grazie a te.
Si tratta di upload da frontend.

Paolo.

**Comment by gmansillo** [comment]
La fix per il problema è sostiture la riga 82 di _com_firedrive/views/documentform/tmpl/default.php_
`<input type="hidden" name="catid" value="<?php echo $this->params->get('default_category'); ?>" />` 
con
` <input type="hidden" name="jform[catid]" value="<?php echo $this->params->get('default_category'); ?>" />` 

La fix sarà già disponibile nel prossimo aggiornamento di Firedrive.
Grazie @cgiardiniere per il tuo aiuto.
