### ISSUE TITLE
Downloadable reserved files

### ISSUE THREAD

**Issue by gquadro** [gmansillo/simple#124]
Reserved files seem to be downloadable even from guest users. In the demo, without logging in, the link

https://www.firedrive.eu/demo/?view=document&id=3&format=raw

download the file that should have been private to the user mario.
The file is not a correct JPG because it has a PHP warning before the actual data.

**Comment by gmansillo** [comment]
Hi,
unfortunately, I had to remove the demo platform because of a server issue. I'm going to check this issue on a test platform. Thank you for reporting it.
