### ISSUE TITLE
errore 403 su upload da backend

### ISSUE THREAD

**Issue by fabster85** [gmansillo/simple#127]
[You forgot to select a file or there was an issue during file upload. ]
Ciao. Riscontro l'errore in oggetto provando l'upload da backend ma solo con alcuni file. I files in questione (soprattutto zip) non hanno nulla di particolare rispetto agli altri che invece vengono caricati correttamente.
Nel codice vedo in quale occasioni viene intercettato l'errore:

```
if ($isNew && !$this->files[$uploadFieldName]["size"])
		{
		throw new Exception(JText::_('COM_FIREDRIVE_NO_FILE_ERROR_MESSAGE'), 403);
	
		}

```
ma non capisco il motivo.

Nessun errore su firebug, nessun errore nei logs.

NB: complimenti per il component. Ottimo lavoro

**Comment by gmansillo** [comment]
Ciao @fabster85, grazie per la segnalazione.
Questi file zip superano la dimensione massima indicata da Joomla! ?

**Comment by gmansillo** [comment]
Closed for lack of feedback
