### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by alkemica** [gmansillo/simple#128]
When clicking one of the front page download button the normal download popup appeared immediately followed by a new popup informing that "the file could not be saved because the source file could not be read". I tried different browsers to exclude that part and also different computers.
The files down 200kb don't have this problem, the problem is only for all type of file over 200kb. 
I use the patest joomla version e latest firedrive version. 
Server: Aruba.

**Comment by gmansillo** [comment]
Hi @alkemica,
it could be an issue with your php.ini configuration file. Please check the value of the following variables:
- `post_max_size`  
- `upload_max_filesize`
