### ISSUE TITLE
Invio email di avviso funziona solo con notify user ed è in lingua inglese

### ISSUE THREAD

**Issue by angi23** [gmansillo/simple#129]
Buongiorno,
su un sito in joomla in produzione con le seguenti caratteristiche:

- Tipo database | mysql
- Versione database | 5.5.56-MariaDB
- Versione PHP | 7.2.10
- Web Server | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.2.10
- WebServer interfaccia PHP | apache2handler
- Versione di Joomla! | Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
- Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

ho installato l'ultima versione di Firedrive, la 5.2.4.

Mi sono accorta che l'invio della mail ai destinatari, quando carico un nuovo documento nell'area personale, non funziona.

Solo flaggando "notify user" viene spedita la mail di avviso e questa è in lingua inglese.
Riesci ad aiutarmi per favore? Come faccio per far ricevere la mail di avviso in automatico e in lingua italiana?

Grazie
Angela

**Comment by gmansillo** [comment]
Ciao Angela, 
nelle impostazioni avanzate del componente (Componenti > Firedrive > Opzioni > Avanzate) è attiva la funzionalità di notifica dei caricamenti?
<img width="441" alt="Screenshot 2019-04-18 at 23 51 10" src="https://user-images.githubusercontent.com/11967003/56393570-2086ba80-6235-11e9-8264-48bfc5a9cf22.png">
Questa opzione dovrebbe essere impostata su "Si" ed essere evidenziata in verde.

Per quanto riguarda la lingua, se hai la certezza che l'utente non stia utilizzando come lingua predefinita l'inglese, potrebbe trattarsi di un bug. Effettuerò delle verifiche ed eventualmente applicherò la correzione.

Grazie per la tua segnalazione.
Giovanni

**Comment by angi23** [comment]
Ciao Giovanni,
certo l'ho impostato correttamente, ma non funziona.

![image](https://user-images.githubusercontent.com/32683562/56413302-55bbf880-6287-11e9-96ce-8faeaac9a99c.png)

Si ho la certezza che l'utente utilizza la lingua italiana in quanto è un utente di test e sono io.

Ti sarei molto grata se mi risolvessi il problema in quanto il cliente ha fretta di partire con l'upload dei documenti.

Inoltre avrei anche la necessità di modificare il link presente nella mail di notifica: è presente un link  alla home del sito. A me piacerebbe che fosse presente il link alla pagina di login, è possibile questo?

Grazie mille per la tua disponibilità.
Buon lavoro, ciao

Angela

**Comment by gmansillo** [comment]
Che visibilità hanno i documenti che carichi? Ho provato ora con "Utenti selezionati" ed ho selezionato la mia utenza: l'email viene inviata correttamente.

L'email è effettivamente sempre in lingua inglese, indipendentemente dall'utente e dalla lingua di amministrazione. Indagherò su questo problema.

Il testo del messaggio può essere modificato a piacimento tramite una override della lingua (https://host-academy.it/tutorial-joomla/how-to-tutorial-joomla/84-come-fare-gli-override-lingua) lavorando sulle stringhe COM_FIREDRIVE_EMAIL_SUBJ (per l'oggetto) e COM_FIREDRIVE_EMAIL_BODY (per il contenuto)'</small>. Attualmente puoi usare il tag {user_fullname}, {document_title}, {author_name} e {site_url} per rendere il messaggio più dinamico.

**Comment by angi23** [comment]
La visibilità è "utenti selezionati". La mail viene inviata solo se clicco su "Notify users" che appare solo dopo che si è caricato e salvato il documento, quindi si perde un po di tempo.

Tra l'altro ho tutto il back office in lingua inglese e non so il perchè.

Facendo l'override della lingua ho risolto il problema della lingua inglese.

**Comment by gmansillo** [comment]
Ho rilevato degli errori nel file di lingua italiana che non ne consentivano il corretto caricamento. 
Ho apportato le modifiche al codice affinchè venga utilizzata la lingua dell'utente per l'invio dell'email di notifica (e come fallback quella predefinita lato sito) anzichè quella del backend.
Farò qualche altro controllo, dopodichè renderò disponibile il pacchetto di aggiornamento.
Grazie ancora per la segnalazione @angi23 !
