### ISSUE TITLE
Trouble Downloading Files

### ISSUE THREAD

**Issue by MarketingMich** [gmansillo/simple#130]
[systeminfo-2019-08-15T13_26_43+00_00.txt](https://github.com/gmansillo/Firedrive/files/3505645/systeminfo-2019-08-15T13_26_43%2B00_00.txt)
I'm using Firedrive 5.2.3 and none of my users are able to download files.  I've set memory_limit = 128M, max_execution_time = 120.  Using SEF urls and the .htaccess file is active.

In Chrome
When a download link is clicked I get "Failed - Network error".  If I then click Resume the download works.

Message In Firefox:
> C:\Users\hillary\AppData\Local\Temp\KhsEFFut.pdf.part could not be saved, because the source file could not be read.
> 
> Try again later, or contact the server administrator.

**Comment by MarketingMich** [comment]
Is this thread being monitored?  The issue is a huge problem for my client. If there isn't a resolution I'll have to locate a different plugin.

**Comment by gmansillo** [comment]
Sorry for delay in reply, I check GitHub issues as frequently as I can. 
The issue you report isn't due to Firedrive but (probably) to the client or to some antivirus software installed on your client's pc.

Let me know if I can help you in some other way.
