### ISSUE TITLE
errore di salvataggio 

### ISSUE THREAD

**Issue by alfred2802** [gmansillo/simple#131]
Ciao, ho da qualche giorno installato Firedrive, ma non riesco a vedere i documenti 
in quanto quando vado a salvare (almeno penso) esce questo messaggio:Attenzione
Campo non valido: Created Date
Campo non valido: Data modifica
grazie e scusa

**Comment by gmansillo** [comment]
Ciao @alfred2802 ,
ho trovato il problema. Puoi trovare la fix nell'ultima commit su github o nel prossimo aggiornamento del componente (ver 5.2.6) quindi ricorda di mantenere attivi gli aggiornamenti automatici in Joomla!
