### ISSUE TITLE
Upload Notifications?

### ISSUE THREAD

**Issue by Cpointcc** [gmansillo/simple#132]
I am looking for a program for file management that will allow email notifications to users who upload/download.  The email may also need to go to multiple users.  Does this program have this functionality?

**Comment by gmansillo** [comment]
At the moment Firedrive doesn't have this functionality.
Anyway, I'm studying Joomla! plugins in order to develop something similar to your request.

**Comment by Cpointcc** [comment]
OK.  I am really struggling to find a comparable replacement to one I am currently using called JFUploader.  It is flash-based and has all the functionality I need.  It has spoiled me to find one that has all the features we need.  Unfortunately with Flash becoming EOL, I need to find one soon.  

I have reviewed at least 10 programs, but NONE of them will allow the email notification configuration by the user, only the global config which doesn't allow me to send an email notification to a specific group or user, only the global admin, and the uploader/downloader.  

Please let me know if you do complete something.

**Comment by Cpointcc** [comment]
I did find a great replacement!  It has been customizied to fit my needs.  The program is J!Extranet.  The Developer is very responsive and open to paid customizations and support.

**Comment by gmansillo** [comment]
Ok. Thank you for your feedback!
