### ISSUE TITLE
Category Description bug

### ISSUE THREAD

**Issue by pnkr** [gmansillo/simple#135]
Even though i set to show the category description. its not showing.

I think that the problem is that you use at  joomla.content.category_default layout which does not fetch the corrent variables

**Comment by gmansillo** [comment]
Hi @pnkr,
I can't reproduce the issue. It seems to show the category description correctly:

![image](https://user-images.githubusercontent.com/11967003/83362171-782bab00-a38f-11ea-85da-cd09cc64b022.png)

<img width="1680" alt="Screenshot 2020-05-31 at 22 40 19" src="https://user-images.githubusercontent.com/11967003/83362223-d22c7080-a38f-11ea-8a87-dcba1d97aa91.png">
