### ISSUE TITLE
Cannot Upload files bigger then 10MB

### ISSUE THREAD

**Issue by Landixus** [gmansillo/simple#138]
we have setup in php.ini and joomla media settings to max file size 50MB

But also a 13MB file comes up with an error:
An error has occurred.
0 You forgot to select a file or there was an issue during file upload.

the browser IE and Chrome upload the file in 5 seconds, then the error comes up

**Comment by gmansillo** [comment]
Please take a look at this article: 
https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-maximum-upload-file-size

**Comment by Landixus** [comment]
Ah i see
