### ISSUE TITLE
Non viene visualizzata la lista dei documenti nelle categorie

### ISSUE THREAD

**Issue by kardo95** [gmansillo/simple#139]
Ciao
Vorrei realizzare un area riservata pubblica (dove tutti gli utenti visualizzano i documenti pubblici) e un area riservata privata (dove l'utente vede file esclusivi per lui). Ho installato Firedrive perchè era free e seguendo i tutorial sembrava molto semplice.
Però dopo aver creato le sezioni visibili solo da chi è registrato, quando vado ad inserire i documenti nelle varie categorie non si visualizzano ne lato utente ne super user, ma controllando tramite ftp i file ci sono , ma se provo ad aprire il percorso da url mi dice (Not Found The requested URL was not found on this server.)
La mia versione di Joomla è Joomla 3.9.19 e uso Astroid come template
Attendo notizie
Grazie per la pazienza

**Comment by gmansillo** [comment]
Ciao, hai dato i permessi di accesso corretti ai file? Mi puoi dare maggiori dettagli sui passi che esegui?

**Comment by kardo95** [comment]
Stupido io che ho selezionato elenco categorie , invece che elenco documenti, per quello non vedevo nulla.
Visto che ci sono ti volevo chiedere se è possibile in qualche modo poter mettere il limite di un download di alcuni file. Vorrei che un utente possa scaricare solo una volta quel documento , è possibile in qualche modo?

**Comment by gmansillo** [comment]
No, purtroppo al momento non é possibile

Il Ven 10 Lug 2020, 17:49 kardo95 <notifications@github.com> ha scritto:
