### ISSUE TITLE
You forgot to select a file or there was an issue during file upload. 

### ISSUE THREAD

**Issue by xploderx** [gmansillo/simple#140]
I cannot upload any files. The following error appears:

An error has occurred.
You forgot to select a file or there was an issue during file upload. 

Joomla 3.9.19
PHP 7.3.19

**Comment by gmansillo** [comment]
Some info about the files you are trying to upload?
Some info about the server and your PHP configuration? (i.e. max upload file size and max post size)

**Comment by xploderx** [comment]
Trying to upload .zip files. Not very big in size. Sometimes even a simple .txt file with nothing in it doesn't upload.
Installed firedrive to another server with similar Joomla setup and the same thing occurs.


OS | Ubuntu 16.04.6 LTS

![php-settings](https://user-images.githubusercontent.com/68104261/87135941-74027f80-c2a3-11ea-9abf-3abde6724147.PNG)

**Comment by gmansillo** [comment]
Did you install any security extension (firewall, etc) on your Joomla environment?

**Comment by xploderx** [comment]
No security extensions (like rsfirewall and stuff) and no other extensions installed in the meantime. Had the front-end download issue - till then I could upload anything I wanted - and updated to the last version which fixed the download issue.

**Comment by gmansillo** [comment]
No idea about what happened. I need to recreate your environment locally in order to investigate. I'm going to do some tests on a generic installation. In the meanwhile, please give me other information about your production environment

**Comment by xploderx** [comment]
If I'm the only one, maybe something is wrong with the server or something. Of course, like what extra info?
