### ISSUE TITLE
Dopo cambio server gli utenti registrati non riescono ad aprire i file caricati con Firedrive

### ISSUE THREAD

**Issue by angi23** [gmansillo/simple#141]
Ciao,
alcuni giorni fa ho spostato un sito su cui è installato firedrive su un altro server con piattaforma Plesk.
Da quel momento gli utenti registrati che prima riuscivano ad accedere alla loro area privata e a scaricare i file non ci riescono più.
Accedono all'area privata ma non scaricano i file. Se provo a caricare un file sul nuovo server questo viene scaricato senza problemi.
Solo i file che erano sul vecchio server non sono più accessibili.
Riesci ad aiutarmi per favore?
Il passaggio del sito l'ho effettuato tramite Akeeba
Informazioni di sistema:
- PHP attivo su | Linux localhost.localdomain 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64
- Tipo database | mysql
- Versione database | 5.5.65-MariaDB
- Collation database | utf8_general_ci
- Collation connessione database | utf8mb4_general_ci
- Versione PHP | 7.2.31
- Web Server | nginx/1.16.1
- WebServer interfaccia PHP | fpm-fcgi
- Versione di Joomla! | Joomla! 3.9.19 Stable [ Amani ] 2-June-2020 15:00 GMT
Grazie, ciao
Angela

**Comment by gmansillo** [comment]
Ciao Angela,
grazie per la segnalazione. Apri un file caricato precedentemente ed un file caricato dopo il trasferimento. Ci sono differenze nella path dei due file?

**Comment by angi23** [comment]
Ciao Gmansillo,
grazie per la tua celere risposta.
Ho guardato sul server e il percorso dei due file è identico.
Noto che da front office, dopo che l'utente si è autenticato, vede i suoi file ma quando li scarica sono vuoti (0 byte). Se vado sul server il file esiste ed è a 18 byte.
Grazie, ciao
