### ISSUE TITLE
Non effettua il download

### ISSUE THREAD

**Issue by marcozeus** [gmansillo/simple#142]
Salve,
ho installato il componente all'interno di un sito in joomla e pre funzionare tutto solo che, una volta scelto il file da scaricare, il tasto download non funzioni ed il suo link è nomedelfile.raw?view=document&id=2 ma semplicemente ricarica la pagina.
Sto sbagliano qualcosa?

**Comment by gmansillo** [comment]
Ciao marcozeus,
grazie per la segnalazione. Puoi inviare un link al sito per una verifica?
Tipicamente i link dovrebbero essere nel formato `index.php?option=com_firedrive&format=raw&....`
