### ISSUE TITLE
Config parameter not working/mixed up

### ISSUE THREAD

**Issue by no64** [gmansillo/simple#144]
Please check all your config parameters in version 5.2.4 

Some are not working at all - like for the "Document settings", there you have e.g. "document_show_created" in the xml but in the file itself it asks for "document_show_document_created", and so on. "document_show_author" is missing at all in the xml.

For category settings some pareameters are mixed up, like "Show Author" and "Show creation date"

**Comment by gmansillo** [comment]
Hi no60, thank you for reporting the issue. In this time I'm very busy so I can't check the issue but if you already fixed it I will thank you if you attach the fixed xml file so I can add it to the source.
