### ISSUE TITLE
Lingua italiana

### ISSUE THREAD

**Issue by marcobracci** [gmansillo/simple#145]
Tre domande:
1) Non riesco a configurare il componente FIREDRIVE in lingua italiana. Come dobbiamo operare?
2) Dobbiamo caricare un file via FTP perchè da "Contenuti/Media" di Joomla ritorna sempre in errore di file non sicuro. Ma l'unico sistema per poi collegarlo al FIREDRIVE è quello di cambiare il nome del file con uno che è già presente in una delle cartelle di "../administrator/components/com_firedrive/uploads". Esiste un'altra procedura più facile?
3) E' possibile sostituire la cartella di upload da "../administrator/components/com_firedrive/uploads" ad una all'interno di "Contenuti/Media" come era nel "Simple File Manager"?
Grazie

**Comment by gmansillo** [comment]
Ciao Marco,
Firedrive utilizza la lingua in cui è impostato il sistema, non c'è modo di impostarne una diversa. Verifica che nella cartella languages del frontend/backend ci siano i 2 file di lingua di firedrive ed eventualmente attiva il debug della lingua nelle impostazioni di sistema di Joomla! per verificare che non ci siano problemi.
Per quanto riguarda le estensioni hai due possibilità: carichi il file con estensione .txt e poi lo rinomini sul db e sul filesystem una volta caricato o (possibilmente più semplice) aggiungi l'estensione da caricare alla whitelist/la rimuovi dalla blacklist di joomla.
Ho spostato la cartella sotto administrator per motivi di sicurezza e, al momento, non c'è modo di cambiarla a meno di non mettere mano al codice del componente.

Spero le informazioni fornite siano state utili a chiarire i tuoi dubbi.
Un saluto,
G.

**Comment by marcobracci** [comment]
Grazie mille,
è infatti un po’ come ho risolto io. Ma in modo più complicato.
Ho infatti caricato in Firedrive un file zip vuoto di prova con lo stesso nome del file giusto che dovevo caricare.
Poi sono andato con FTP e ho sostituito questo file di prova con il file zip giusto.
Funziona tutto, tranne la dimensione in kilobyte del file. (resta visualizzata quella dello zip vuoto)
Mi piacerebbe adottare il tuo suggerimento di caricare il file con estensione .txt, e poi rinominare il file con FTP.
Ma non ho capito e non so come fare a rinominare il file sul filesystem una volta caricato (sempreché la rinominazione del db è sufficiente quella fatta con FTP)
Per quanto riguarda invece la seconda opzione più semplice (whitelist e blacklist) non so davvero cosa devo fare e cosa significa “whitelist” e “blacklist”
Se hai tempo e voglia di dirmi cosa significa te ne sarei davvero grato.
La “donazione” è in ogni caso sicuramente meritata.
Grazie e cordialità
Marco Bracci (Firenze)
335 440468

**Comment by gmansillo** [comment]
Ciao Marco, grazie ancora per la segnalazione.
Effettivamente nel file di lingua ci sono dei problemi. Le linee 123, 125 riportano un doppio apice di apertura di troppo mentre nella 170 manca il doppio apice di apertura.

**Comment by gmansillo** [comment]
Per quanto riguarda il file che non riesci a caricare, prova ad alzare la dimensione massima a 200MB. E' molto strano, ma il sistema potrebbe considerare la dimensione originale dei file anzichè quella dello zip.
