### ISSUE TITLE
Error Upload file ZIP o RAR con file maggiori di 25MB

### ISSUE THREAD

**Issue by camillocam** [gmansillo/simple#146]
Buonasera,
ho una sito web con la sua estensione Firedrive  v.5.2.4 e Joomla 3.9.24 hosting condiviso e PHP versione 7.4
Nel momento in cui carico file di piccole dimensioni di qualsiasi tipo non ci sono problemi, per i file maggiori di 25MB di tipo RAR o ZIP non me li fa caricare. Lo stesso file rinominato AVI o DOC riesce a caricarlo.
![Cattura](https://user-images.githubusercontent.com/3796508/106030587-a30d0100-60ce-11eb-903b-a13d4a7447ca.PNG)

**Comment by camillocam** [comment]
Il file PHP.ini 
max_execution_time 300
max_input_time 60
memory_limit 256M
max_input_vars 5000
output_buffering 4096
post_max_size 50M
upload_max_filesize 50M
zlib.output_compression On
short_open_tag Off

**Comment by gmansillo** [comment]
Ciao,
grazie per la segnalazione. In realtà Firedrive non pone nessuna
restrizione di questo tipo. Potrebbe essere stato installato qualche
antivirus sul server che magari non è in grado di effettuare la scansione
di archivi più grandi di una certa dimensione?

Il giorno mer 27 gen 2021 alle ore 18:39 camillo860 <
notifications@github.com> ha scritto:

**Comment by camillocam** [comment]
Ciao,
ho fatto un'installazione nuova di Joomla 3.9.15 con PHP 7.3 e Mysql, non ho firewall e ho impostato il php.ini a 100MB di file upload. Ho impostato nella configurazione di Joomla la possibilità di caricare file zip e rar . I file non vengono caricati. Puoi provare a ricreare il bug ?

 :(

**Comment by gmansillo** [comment]
Ciao Camillo, se vuoi proviamo a vederlo insieme. Contattami da qui
https://firedrive.eu/it/contacts con la tua email.

Il giorno gio 18 mar 2021 alle ore 17:48 camillo860 <
***@***.***> ha scritto:
