### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by isidoroi** [gmansillo/simple#148]
Is the project still active?
Thank You

**Comment by gmansillo** [comment]
Hi,
do you want to collaborate?

**Comment by isidoroi** [comment]
Purtroppo non credo di essere ancora all'altezza di poter collaborare al
progetto, piuttosto al momento la mia richiesta era basata sull'utilizzo
dell'estensione joomla che non risulta essere aggiornata da diverso tempo e
pertanto prima di pensare di utilizzarla in un nuovo progetto , mi chiedevo
se anche in previsione dell'uscita di joomla 4, questa fosse ancora attiva.
Grazie a prescindere dalla risposta.
