### ISSUE TITLE
Will there be a FireDrive version for Joomla 4 ?

### ISSUE THREAD

**Issue by Ralleff** [gmansillo/simple#150]
**Note: for support questions, please use the [Joomla! Forum](http://forum.joomla.org)**. This repository's issues are reserved for feature requests and bug reports.  

**Language:** you can describe the issue in English (preferred), Italian or Spanish.

* **I'm submitting a ...**
  - [ ] bug report
  - [ x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A feature or an upgrade, actually.
  

* **What is the current behavior?**
FireDrive only available for Joomla 3.x. Does not work on Joomla 4.
  

* **If the current behavior is a bug, please make sure to provide all the information needed to understand the bug so that someone can help** 

- [ ] Provide the steps to reproduce the issue
- [ ] Provide **screenshots** where appropriate
- [ x] What's the **version** of Firedrive you're using? the latest...
- [ ] What's the **version** of Joomla!/PHP/MySQL you're using? Joomly 4.2.7 / PHP 8.0
- [ ] Does this occur only on certain browsers?

* **What is the expected behavior?**
Have a working Firedrive version for Joomla 4.

* **What is the motivation / use case for changing the behavior?**
Continue historical projects with FireDrive

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for me to have context, eg. stackoverflow, gitter, etc)

**Comment by ArnoutVos** [comment]
We are using FireDrive extensively and because this extension is not upgraded yet for Joomla 4, it currently holds us back from upgrading to Joomla 4.
