### ISSUE TITLE
Invalid address - Dopo tentativo di nuovo inserimento

### ISSUE THREAD

**Issue by Babbicciu** [gmansillo/simple#18]
Salve, dopo aver provato a fare un nuovo inserimento, compare un messaggio di errore

---

Si è verificato un errore.

```
0 Invalid address: 
```

---

![errore simple file manager](https://cloud.githubusercontent.com/assets/19651052/15651768/d22662c4-2681-11e6-8147-d73301d1bdb0.png)

Allego immagine per spiegarmi meglio.

Ultimamente ho eseguito solo l'aggiornamento di Joomla, la versione in uso ora è 3.5.1
Leggo di una news riguardante il file htaccess rilasciato dagli sviluppatori Joomla. C'è qualcosa che è cambiato e va modificato?
Grazie dell'aiuto

**Comment by gmansillo** [comment]
Ciao Babbicciu,
devi aggiornare anche la versione di Simple File Manager, altrimenti dovrai disattivare l'invio delle email.
