### ISSUE TITLE
Cancel button not working in backend view

### ISSUE THREAD

**Issue by gmansillo** [gmansillo/simple#2]

**Comment by gmansillo** [comment]
Fixed since 5.0.7

**Comment by giolecce** [comment]
sorry but i have downloaded from the site the version 5.0.6 and bug is there yet.

**Comment by gmansillo** [comment]
Hi giolecce,
maybe you missed my previous comment: the fix will be available from the next release (5.0.7).

**Comment by giolecce** [comment]
## Good and  when is it ready?

Inviato da Libero Mail per Android Mercoledì, 20 Aprile 2016, 11:40AM +02:00 da Giovanni < notifications@github.com> :

**Comment by gmansillo** [comment]
Soon. I would like to fix the other bugs before releasing an update.

**Comment by giolecce** [comment]
## Ok thank a lot!!!

Inviato da Libero Mail per Android Mercoledì, 20 Aprile 2016, 11:56AM +02:00 da Giovanni < notifications@github.com> :

**Comment by gmansillo** [comment]
Simple File Manger 5.0.7 is now available
