### ISSUE TITLE
Visualizzazione Navigazione e Ordine Articoli

### ISSUE THREAD

**Issue by SiliconValleyComputer** [gmansillo/simple#21]
Hi,

I have two problems:
1. Into SimpleFileManager Category view Menu navigation is hidden and I can show only 20 files...
2. How can I order by default date descending??

Thanks

**Comment by gmansillo** [comment]
Hi, which version of SFM are you currently using?
I should have fixed that bug in release 5.0.9 (see ticket #17)

**Comment by SiliconValleyComputer** [comment]
Thank you so much!!!!
