### ISSUE TITLE
MP3 stops playing

### ISSUE THREAD

**Issue by ReneDaanen** [gmansillo/simple#22]
Hi @gmansillo,

I've user Simple File Manager to upload MP3's to show them to just one usergroup logged in to my Joomla site. 
I've enabled the option 'Featured', so users are able to listen to the music directly, withouten downloading first. 
From different users (including myself), I've heard that almost anytime they play a song, somewhere during the song, the song restarts from the beginning. Note that it is not always (of never) on the same position. 
It dan be somewhere near the beginning, near the end, or somewhere in between.
It also happens on multiple MP3's, so it doesn't seem to be file dependent.

Are you aware of such a problem?
Can Simple file manager cause this?

Thanks in advance,

René Daanen.

**Comment by gmansillo** [comment]
Hi ReneDaanen, i'm not able to help you because I can't identify the cause of your problem in Simple File Manager.
