### ISSUE TITLE
Change Title in Frontend forces unpublished State

### ISSUE THREAD

**Issue by ghost** [gmansillo/simple#23]
Hello, 

after change/edit a title of an existing File in Frontend, the file will be set to unpublished. Please follow the screenshots. 

![changetitle4](https://cloud.githubusercontent.com/assets/11690861/16762992/3a691932-4827-11e6-85cc-9a2333dd8ecd.png)
![changetitle3](https://cloud.githubusercontent.com/assets/11690861/16762993/3a69c80a-4827-11e6-98fd-379989c45eb9.png)
![changetitle2](https://cloud.githubusercontent.com/assets/11690861/16762994/3a6a002c-4827-11e6-9b27-5e48997ba850.png)
![changetitle1](https://cloud.githubusercontent.com/assets/11690861/16762995/3a6aba3a-4827-11e6-8f35-a2dee94fd472.png)

Thx, 
Kai

**Comment by gmansillo** [comment]
Hi Kai, wichh version of SFM are you currently using?
I noticed also that some language string are missing in your translation file. :(

**Comment by ghost** [comment]
Hi Giovanni, 
I am using latest version of SFM Version 5.0.9.

**Comment by gmansillo** [comment]
Please refer to issue #37
