### ISSUE TITLE
Status-Icon

### ISSUE THREAD

**Issue by ghost** [gmansillo/simple#24]
Hello, 

it is not possible to see if the object state is published or not. 

![state](https://cloud.githubusercontent.com/assets/11690861/16763156/ef18208a-4827-11e6-9fd9-587ea077f927.png)

thx,
Kai

**Comment by gmansillo** [comment]
Thank you for reporting the issue. I'll try to fix it in the next update

**Comment by gmansillo** [comment]
Thank you for reporting the issue. I'll try to fix it in the next update

**Comment by gmansillo** [comment]
I wasn't able to reproduce the issue in joomla 3.6 so I have to suppose there is no bug
![evidence](https://cloud.githubusercontent.com/assets/11967003/19628630/d8a21c8e-9962-11e6-9f0d-5df16146f7c1.png)
