### ISSUE TITLE
Bug with File saving location and download button.

### ISSUE THREAD

**Issue by markholland8** [gmansillo/simple#25]
Ok i have 2 issues,
1.  When i used to save any documents it saved to:
   images/simplefilemanager/576122c8d0d482.60220510/Forman Poem translation.pdf

I have just updated to version 5.0.9 and now it saves to:
/home/********/public_html/administrator/components/com_simplefilemanager/uploads/5788ca0d933124.32094453/filename.txt

Why would the save location change and how can i change it back?
1.  when i try and download a document i have previously uploaded using the admin panel (components>simple file manager> select article>hit download button) i get the following error

An error has occurred.
 404 View not found [name, type, prefix]: download, html, simplefilemanagerView
 Return to Control Panel

Thank You

**Comment by gmansillo** [comment]
Hi markholland8,
did you installed SFM 5.0.9 on an existing 4.x.x? Those versions are not compatible! 
The quickest solution now is to restore a previous backup.

**Comment by markholland8** [comment]
Nope it is on Joomla! 3.6.0

**Comment by gmansillo** [comment]
I didn't test simple file manager 5.0.9 on Joomla! 3.6 yet, but it seems that you have installed simple file manager 5.0.9 without removing a previous installation of simple file manager 4, and this fact caused your issue. As I already said, those version aren't compatible among them.

**Comment by markholland8** [comment]
so whats the solution?

**Comment by gmansillo** [comment]
You have to restore a previous backup

**Comment by markholland8** [comment]
of the whole website?

**Comment by gmansillo** [comment]
You can also restore only component folders and tabels, leaving the rest unchanged

**Comment by markholland8** [comment]
i dont have this ability!!!! looks like im screwed and need to start again

**Comment by gmansillo** [comment]
Why do you think this? You can easily delete component files (from both admin and frontend side) and tables (from database) and then you can replace them with the ones you have in your backup! If don't have a backup available, you can also uninstall Simple File Manager and reinstall it but although the rest of your website won't be touched, in this way you will lost all your Simple File Manager entries.

**Comment by markholland8** [comment]
that's the problem i have 100's of files that i will lose entries for, i am afraid "simple" is not so simple i will need to start again from scratch as i am not very god with database although i can reinstall the component files i have backups everyday for one month.

**Comment by gmansillo** [comment]
I can't find any complication due to Simple File Manager in this. You installed a wrong update and now you can only restore a backup to solve the issue. If you aren't able to do it, you can ask for help to your provider or on any forum dedicated to joomla.
