### ISSUE TITLE
Button download in backend edit view causes a 500 - view not found

### ISSUE THREAD

**Issue by chmst** [gmansillo/simple#28]
There is a download button attached to the file-input field. Why? Activating this button causes an error 500 - view download not found

**Comment by gmansillo** [comment]
Hi chmst, are you talking about the download button in backend view? It's useful for admins who wants to manually download files atfer they've uploaded them. Wich version of SFM are you using? Did you update it from a previous version in the past?

**Comment by chmst** [comment]
it is a new installation, 5.0.9, no update.

The download button is

<a target="_blank" class="btn btn-primary"
href="index.php?option=com_simplefilemanager&amp;view=download&amp;id=5">
<i class="icon-download">&nbsp;</i></a>

But as there is no view "download" in the backend, you get a error 500 -> view not found.

**Comment by gmansillo** [comment]
Thank you chmst, i'm going to fix it in the next update.

**Comment by mrdanne** [comment]
Hi, when is the update coming? Have the same issue and can not download from the front page either! 
Running 5.0.9 and Joomla 3.6.2

**Comment by gmansillo** [comment]
Sorry for delay. I need to get togheter some different fixings before releasing the next update. In the meantime you can fix it yourself editing **line 76** of **administrator\components\com_simplefilemanager\views\simplefilemanager\tmpl\edit.php** in this way:

`href="index.php?option=com_simplefilemanager&task=download&id=<?php echo $this->item->id; ?>"><i`

Lines 75-77 will become as follow:

`<a target="_blank" class="btn btn-primary"`
`href="index.php?option=com_simplefilemanager&task=download&id=<?php echo $this->item->id; ?>"><i`
`class="icon-download">&nbsp;</i></a>`

Hope this helps.

**Comment by mrdanne** [comment]
Hi,

Now I am getting **File not found** in the backend :(

And in the front end nothing happens when clicking on the link.

Any other idea?

**Comment by gmansillo** [comment]
Is it a fresh installation or did you update it from a previous version?

**Comment by mrdanne** [comment]
I edited from my previous website.

**Comment by gmansillo** [comment]
I think you have lost referencies to uploaded documents into your database.
Can you check it?

Il 28 set 2016 08:52, "mrdanne" notifications@github.com ha scritto:

**Comment by mrdanne** [comment]
Hm, how do I check that?

I also tried to create a new download, but that didn't work either. Same same

**Comment by mrdanne** [comment]
Found it... in phpmyadmin

`/var/www/NordicIntranet/administrator/components/com_simplefilemanager/uploads/57eb67d4e17184.72779983/PERSONALHANDBOK CRAWFORD_2014-10_1.1.pdf`

Looks OK and it have a path.
Joomla says that the database is OK.

**Comment by mrdanne** [comment]
Seem a bit odd that the /var/www is listed... If I paste this link in I can download the file: http://nordic/administrator/components/com_simplefilemanager/uploads/57eb67d4e17184.72779983/PERSONALHANDBOK%20CRAWFORD_2014-10_1.1.pdf

**Comment by mrdanne** [comment]
Can I try something else to fix this issue?

**Comment by gmansillo** [comment]
If your problem is the "/var/www" prefix, you can execute a simple script in phpmyadmin that removes the wrong part from each sfm table entry.  
E.g. you can try using:
`UPDATE jos_simplefilemanager
SET    file_name= replace(file_name, '/var/www', '')
WHERE  file_name LIKE '/var/www%';`  
Remember to replace jos with your table prefix and to make a db backup before any operation!

**Comment by mrdanne** [comment]
It is very strange as the plugin have worked flawless before and suddenly this happens...

When you click on the download link on the front end it look like this: http://nordic/index.php/se/personal/personalhandbok?task=download&id=3 

So isn't the issues somewhere in the script?

**Comment by gmansillo** [comment]
I think you did an unsupported update of SFM, i.e. from a 4.x.x to a 5.x.x 😨
During this operation you corrupted db data and also system files. The only thing you can do now is to restore a working backup.

**Comment by mrdanne** [comment]
Unsupported!?!? And how should I have know this if that is the case?

**Comment by gmansillo** [comment]
I'm aware that there isn't a lot of documentation about Simple File Manager, but I often write about it on Joomla!  forums. The different version number should have been alerted you before you continue with the update. Anyway it's not difficult to restore a joomla backup, expecially if you are familiar with Akeeba component.

**Comment by gmansillo** [comment]
Anyway, you gave me a brilliant idea today: i'll add a version check at installation time since the next release in order to avoid similar problem in the future. Thank you mrdanne!

**Comment by mrdanne** [comment]
That is very bad news!
An update to a higher version of basically anything usually works perfectly... 

Could also be an idea to write on your homepage that an upgrade from 4 to 5 isn't possible then. Luckily for me I don't have that much files so it will only take like an hour or so to upload it to another file manager like jdownload.

**Comment by gmansillo** [comment]
You would be right about it if we were dealing about an **update** but we are talking about a **migration**: the first digits of a release number are always (so not only in this case) representing the major version. A different major version indicates incompatible changes. It's a development standard! 😄 

An useful reference: http://semver.org/

**Comment by mrdanne** [comment]
I only have 1 site and haven't migrated anything.

**Comment by gmansillo** [comment]
If you never migrated from SFM 4.x.x  to 5.0.9, someone did it for you. I'm absolutely sure about it because this href: `task=download&id=3` only appears in SFM 4. 
There aren't other logic explanations to what happened to your site.
I would like to help you further, but the only thing you can do now is to restore a previous backup.

**Comment by mrdanne** [comment]
All I did is to install the newest SFM in joomla when I noticed the files were unable to download... 

But it doesn't matter if it is impossible to fix it now.
