### ISSUE TITLE
500 Page after update to joomla 3.6.2

### ISSUE THREAD

**Issue by wschaapman** [gmansillo/simple#30]
The menu item of all documents is giving an 500 page. It looks like you can not show all documents anymore, you have to choose an category?

**Comment by gmansillo** [comment]
Hi, wich version of Simple File Manager are you using?

**Comment by mrdanne** [comment]
Same here, 5.0.9 and Joomla 3.6.2

**Comment by psike73** [comment]
5.0.9 and Joomla 3.6.2 here too. I get the document list displayed ok. If logged in with permission to edit clicking any of the admin buttons causes a 500 error.

> If difficulties persist, please contact the System Administrator of this site and report the error below.
> 500 You are not authorised to view this resource.

It also seems to have logged the user out of joomla as when I go back to another page I found I'm logged out.

**Comment by gmansillo** [comment]
Can you update to 5.0.12 and retry please?

**Comment by wschaapman** [comment]
I already solved it by using an other component.

Met vriendelijke groet,

Wilbert Schaapman
wilbert@wilbertschaapman.nl

---

Van: Giovanni notifications@github.com
verzonden: 15 nov. 2016 8:24 p.m.
Aan: gmansillo/simplefilemanager
Cc: wschaapman; Author
Onderwerp: Re: [gmansillo/simplefilemanager] 500 Page after update to joomla 3.6.2 (#30)

Can you update to 5.0.12 and retry please?

##

**Comment by gmansillo** [comment]
I'm glad you found a solution but I can't understand how can this information help me solving the issue.... 😓

**Comment by wschaapman** [comment]
This problemen had been reported months ago..this is your First reaction...
not that kind of good service..

Please try to solve by yourself.
Goodluck

Met vriendelijke groet,

Wilbert Schaapman
wilbert@wilbertschaapman.nl

---

Van: Giovanni notifications@github.com
verzonden: 15 nov. 2016 8:33 p.m.
Aan: gmansillo/simplefilemanager
Cc: wschaapman; Author
Onderwerp: Re: [gmansillo/simplefilemanager] 500 Page after update to joomla 3.6.2 (#30)

I'm glad you found a solution but I can't understand how can this information help me solving the issue.... ?

##

**Comment by gmansillo** [comment]
It was impossible to reproduce the issue since you never provided enough details for doing it...
Anyway I'll continue to do my best in order to improve this free support service.

Thank you for your patience.
