### ISSUE TITLE
Site crash SFM Joomla 3.62

### ISSUE THREAD

**Issue by remosant** [gmansillo/simple#31]
Working with SFM and Joomla 6.32...
Selected old documents and  put Them into the Recycle Bin...
Then selected deleted item.......
With command Delete the Site suddenly  crash.
Looking by Filezilla the entire directory Administrator is EMPTY !!!!!
Is There a relation between these events???
Thanks a lot

remosant@libero.it

**Comment by gmansillo** [comment]
I'm going to check it

Il 04/set/2016 16:11, "remosant" notifications@github.com ha scritto:

**Comment by gmansillo** [comment]
Hi, i can't get the error you are reporting while emptying trash in Simple File Manager 5.0.9 on Joomla 3.6.2 so i think yoour problem is due to external causes.

**Comment by remosant** [comment]
thanks a lot.... 

Inviato da iPhone

**Comment by gmansillo** [comment]
Thank you for contacting me!
