### ISSUE TITLE
stato documenti

### ISSUE THREAD

**Issue by salvo72** [gmansillo/simple#32]
ciao, avrei  2 quesiti:

1)la necessita di rinominare lo stato documenti , ma guardando il file di lingua non sembra possibile

2) desidererei che l'user che ha l'accesso a determinati documenti privati  riceva email al cambio di stato

Puoi darmi supporto?

grazie

**Comment by gmansillo** [comment]
Ciao,
Simple File Manager condivide gli stati con Joomla. Per modificare gli stati di Simple File Manager dovrai quindi editare i file di lingua di joomla e non quelli del componente, a meno che non procedi con una override della view e dei file di lingua.

Al momento non è previsto nel componente l'invio di notifiche al cambio di stato ma solo al caricamento.
