### ISSUE TITLE
errore 500 View non trovato

### ISSUE THREAD

**Issue by sfeniello** [gmansillo/simple#33]
entrando in modifica del documento e cliccando sul pulsante vicino al percorso del file caricato ottengo il seguente errore 
 500 View non trovato [name, type, prefix]: download, html, simplefilemanagerView
Call stack
# Function    Location

1   JApplicationCms->execute()  /web/htdocs/www.faccettagroup.com/home/administrator/index.php:51
2   JApplicationAdministrator->doExecute()  /web/htdocs/www.faccettagroup.com/home/libraries/cms/application/cms.php:257
3   JApplicationAdministrator->dispatch()   /web/htdocs/www.faccettagroup.com/home/libraries/cms/application/administrator.php:152
4   JComponentHelper::renderComponent() /web/htdocs/www.faccettagroup.com/home/libraries/cms/application/administrator.php:98
5   JComponentHelper::executeComponent()    /web/htdocs/www.faccettagroup.com/home/libraries/cms/component/helper.php:380
6   require_once()  /web/htdocs/www.faccettagroup.com/home/libraries/cms/component/helper.php:405
7   JControllerLegacy->execute()    /web/htdocs/www.faccettagroup.com/home/administrator/components/com_simplefilemanager/simplefilemanager.php:18
8   SimplefilemanagerController->display()  /web/htdocs/www.faccettagroup.com/home/libraries/legacy/controller/legacy.php:728
9   JControllerLegacy->display()    /web/htdocs/www.faccettagroup.com/home/administrator/components/com_simplefilemanager/controller.php:136
10  JControllerLegacy->getView()    /web/htdocs/www.faccettagroup.com/home/libraries/legacy/controller/legacy.php:645

le versioni utilizzate sono joomla 3.5.1 
Simple File Manager 5.0.9

Inoltre vorrei capire se c'è modo di poter visualizzare in anteprima il file caricati.

Grazie

**Comment by gmansillo** [comment]
Duplicato: #28 
Non è possibile visualizzare in anteprima i file caricati, a meno che il browser non sia impostato per visualizzare i documenti prima di scaricarli (sarà è necessario un plugin per ogni formato file)

**Comment by sfeniello** [comment]
quindi il componente non presenta una soluzione che permetta una verifica per controllare se i file caricati sono corretti ?

**Comment by gmansillo** [comment]
Si, è possibile verificarlo.
Se ci sono errori nel caricamento, il file non viene registrato sul database. Se durante il caricamento ci sono state delle interferenze che hanno portato ad una corruzione del contenuto del file, invece, lo si può controllare andando a confrontare l'md5 del file che Simple File Manager crea automaticamente dopo l'upload.
Lato amministratore, infine, è possibile scaricare e visualizzare il file precedentemente caricato per verificare manualmente che il file sia stato caricato senza errori.

**Comment by sfeniello** [comment]
scusa proprio lato amministratore non trovo nulla che indica che posso scaricare il file, precedentemente caricato, e visualizzarlo. l'mica cosa che vedo è quel pulsante vicino al path del file,  come da schermata, che non funzione anzi mi da proprio quell'errore 500 
mi sai indicare dove sta questa opzione?
![schermata 2016-09-22 a 15 01 23](https://cloud.githubusercontent.com/assets/22170579/18749139/c3444240-80d5-11e6-87a4-6ab2bb569803.png)

**Comment by gmansillo** [comment]
Il pulsante di download è quello che stai già utilizzando. Ha un'icona abbastanza intuitiva..

**Comment by sfeniello** [comment]
```
E non funziona come si può risolvere?

Il 22/09/16 15.18, Giovanni ha scritto:


  Il pulsante di download è quello che stai utilizzando già.
  —
    You are receiving this because you authored the thread.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gmansillo/simplefilemanager","title":"gmansillo/simplefilemanager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gmansillo/simplefilemanager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gmansillo in #33: Il pulsante di download è quello che stai utilizzando già."}],"action":{"name":"View Issue","url":"https://github.com/gmansillo/simplefilemanager/issues/33#issuecomment-248900747"}}}
```

**Comment by gmansillo** [comment]
Il bug è già stato segnalato nella discussione che ti ho linkato precedentemente: appena sarà disponibile una fix pubblicherò l'aggiornamento.

Fammi sapere se c'è qualcos'altro che posso fare per te :smile:
