### ISSUE TITLE
File shared with multiple user

### ISSUE THREAD

**Issue by carlotarget** [gmansillo/simple#34]
Hi,
there's a way to share a single file with several users that are in different groups?

**Comment by gmansillo** [comment]
Hi,
unfortunately there isn't a way to to do it directly in Simple File Manager :cry:  Did you try to gather all those groups under an unique parent group and to choose the parent group in the document settings?

**Comment by carlotarget** [comment]
Ciao Giovanni, ma sei Italiano?

2016-09-26 11:25 GMT+02:00 Giovanni notifications@github.com:

**Comment by gmansillo** [comment]
Yes, I am, but I prefer to write in English here, in order to improve my
writing skills and to make Github discussions about simple file manager
available to the most of the users.

Thank you for understanding :smile:

Kind regards,
Giovanni
