### ISSUE TITLE
utente manager 

### ISSUE THREAD

**Issue by salvo72** [gmansillo/simple#36]
ciao

devo fare usare il componente al proprietario del sito come utente manager

in effetti ho impostato i permessi relativi a questo profilo utente e adesso l utente manager ha pieno accesso al componente

ma al momento di assegnare un documento ad un singolo cliente , arrivato alla lista degli utenti non ho accesso (non vedo la lista con conseguente alert di mancato permesso)

chiaramente ho accesso solo come super admin

come risolvo?

grazie

**Comment by gmansillo** [comment]
Ciao, la selezione degli utenti è una funzionalità nativa di joomla: dovresti provare a smanettare tra le ACL del componente "utenti".
