### ISSUE TITLE
Upload file da frontend

### ISSUE THREAD

**Issue by marco87sr** [gmansillo/simple#37]
Ciao! Complimenti per l'estensione! utile e fatta bene!

Ho visto che è possibile caricare file da frontend. Però se provo a caricare un file devo sempre comunque "approvarlo" da backend in quanto risulta sospeso. C'è qualche soluzione?

grazie mille

**Comment by gmansillo** [comment]
Ciao Marco,
se da front-end accedi come amministratore hai lo stesso problema?

**Comment by marco87sr** [comment]
si, ho provato anche da super user ed il problema si presenta lo stesso!

**Comment by gmansillo** [comment]
Ciao Marco, ho verificato il problema ed ho apportato la correzione.
Il codice aggiornato sarà disponibile a partire dalla versione 5.0.10

Grazie per la tua segnalazione!

**Comment by marco87sr** [comment]
Ciao Giovanni, grazie per aver corretto il bug :). È possibile avere la versione "corretta" fin da subito? Ovviamente effettuerò la donazione.

Saluti

**Comment by gmansillo** [comment]
Ciao Marco, naturalmente è già disponibile la versione corretta senza backlink.
Qualche giorno di pazienza e rilascio anche il pacchetto gratuito su GitHub!
