### ISSUE TITLE
Unpublished documents are shown in frontend

### ISSUE THREAD

**Issue by rcaregn** [gmansillo/simple#38]
Ciao, complimenti per il prodotto semplice ed essenziale...purtroppo i files vengono pubblicati anche se disabilitati...come si può risolvere ? grazie

**Comment by gmansillo** [comment]
This would be a serious issue!
Let me verify and i'll try to fix it as soon as possible.

**Comment by gmansillo** [comment]
Hi,
I'm not able to reproduce the issue. On my test platform public unpublished documents are not shown in frontend. Can you give me more details? If not, I must label the issue as invalid.

**Comment by rcaregn** [comment]
Ciao, scusa il ritardo nella risposta, ho avuto qualche problema nella posta. Nel frattempo ho reinstallato il modulo e adesso sembra funzionare correttamente, grazie e scusa ancora ...
