### ISSUE TITLE
BUG Simple File Manager

### ISSUE THREAD

**Issue by marcocolarossi** [gmansillo/simple#40]
Come potete vedere dal sito http://www.scuolamozart.gov.it/sito/genitori/avvisi-alle-famiglie?view=simplefilemanagers non riusciamo a mettere i file in ordine poiché simple file manager ritiene che 10 sia più piccolo di 2. Non sappiamo come risolvere.

**Comment by gmansillo** [comment]
I can't find any issue in that: this is the expected behavior. It's called lexicographic sorting. More info here: https://en.m.wikipedia.org/wiki/Lexicographical_order
