### ISSUE TITLE
Impossibile trovare pacchetto di installazione (Simple File Manager) GMansillo

### ISSUE THREAD

**Issue by GiorgioBertuzzi** [gmansillo/simple#43]
Buonasera,

ho un problema con l'installazione di Simple File Manager dalla ultima versione di Joomla 3.

In soldoni installando da .zip ricevo la seguente risposta:

Errore

Unable to write entry
Impossibile trovare pacchetto di installazione

Magari potessi avere un suggerimento da GMansillo ne sarei molto grato.

Giorgio

**Comment by gmansillo** [comment]
Hi,
it seems that Joomla has problems with some compressed files formats. You can try extracting the zip package and compressing extracted files again as a zip. Then retry the installation procedure.

Does this solution work for you?

**Comment by GiorgioBertuzzi** [comment]
I'm so sorry it does not work properly. Any suggestion? Please.

Thanks in advance

Giorgio

**Comment by gmansillo** [comment]
Ok. In this case you have to check file and folder permissions. Then check also log and tmp path in configuration.php. Also try to disable the FTP layer.

As last chance try to proceed with the manual installation (refer to this article: https://docs.joomla.org/Installing_an_extension)

**Comment by GiorgioBertuzzi** [comment]
Sorry I'm late this mornig for answering. I'll try your suggestion and I'll be back with a check.

Thanks

Giorgio

**Comment by GiorgioBertuzzi** [comment]
Manual Upload failed: "Errore critico trasferimento file",... ufffff :(

**Comment by gmansillo** [comment]
What happens if you try to install another extension?
You can try with this: https://extensions.joomla.org/extension/what-nothing

**Comment by GiorgioBertuzzi** [comment]
I have no problem with any kind of extension. Only with your extension, that's a pity 'cause I love it. It is easy and perfect for me. Perfectly installed "nothing" and now?

**Comment by gmansillo** [comment]
😢 That's very strange!
Are you working remotely or on a local lamp?

**Comment by GiorgioBertuzzi** [comment]
I'm working remotely. Would you like enter in my web site may be you can solve it soon.

**Comment by gmansillo** [comment]
Can you take a look to System -> System info -> Folder permissions?
Reading some forums online, it seems that this error message means that Joomla cannot unpack the installation zip to the temporary directory so the main problems can be:  
- wrong permissions of Joomla's tmp directory
- tmp directory isn't in the right place (maybe is over the root of public space?)
- there isn't enough free disk space to unpack the zip

Since you tried also with the manual installation process and you got a similar error ("Errore critico trasferimento file" - it means that the system cannot copy a file) i think you have a permission issue on all the webroot. Can you reset permissions via your hosting control panel?

Optimal values are: file -> 644, folder -> 755

**Comment by GiorgioBertuzzi** [comment]
I check it out to folder permissions from system info and are ok, also tmp folder file -> 644, folder -> 755

It's a mistery

**Comment by brandinal** [comment]
Hello!
I have the same problem, I tried to install it from the web, through url, through installation package, and I've installed it in two different web and it does not work.

**Comment by brandinal** [comment]
...I'm working on Local

**Comment by gmansillo** [comment]
I'm about to release an update. I hope this will fix the issue

**Comment by GiorgioBertuzzi** [comment]
I thank you Mr. Giovanni. Waiting for your release update. Regards

**Comment by brandinal** [comment]
Thank you very much. A very good customer service.
Do you know the release date? That way i'll be mindful

**Comment by gmansillo** [comment]
Tonight ;-)

**Comment by gmansillo** [comment]
This time I packed source files manually. Please let me know if now it works for you!
Version number is 5.0.12

**Comment by GiorgioBertuzzi** [comment]
Hi Giovanni, it's impossibile find this new release. It wasn't in Joomla Extension Directory, nor in your web site.

Please check it again

**Comment by gmansillo** [comment]
Hi Giorgio,
please download it from https://github.com/gmansillo/simplefilemanager/releases

**Comment by GiorgioBertuzzi** [comment]
Nice! It works fine thank youuuuuu ;)

Bella, si installa ottimamente! Complimentoni :)
P.S. ma il faccione a termine installazione è il tuo? ;) hahahaha

Grazie Giovanni!

**Comment by gmansillo** [comment]
Fortunately it's not me 😉 
I'm glad the issue was solved. I would really appreciate if you help me leaving a good review about the component at https://extensions.joomla.org/extension/simple-file-manager

Thank you!

**Comment by GiorgioBertuzzi** [comment]
Ok,... I will as soon as possible 

Now I have to study your nice work

Best regards

Giorgio

**Comment by brandinal** [comment]
Hi. Thank you very much for the speed. The program installed perfectly. Now I'm going to make a positive review

**Comment by gmansillo** [comment]
Thank you Miguel!

**Comment by brandinal** [comment]
I am not a developer, but I am translating the application into Spanish. If you need help in this aspect we could talk about it. Regards

**Comment by gmansillo** [comment]
Hi Miguel,
I inserted additional translation files in the past but it was very difficult to update them in short time at any new update, then I started asking to contributors to share their translations in joomla! local community websites (e.g. joomla.it, joomla.fr, etc.). I will be grateful if you can do the same. 👍
