### ISSUE TITLE
Zip files not uploading

### ISSUE THREAD

**Issue by Romenum** [gmansillo/simple#49]
Hi!
I'm trying to upload zip and rar files but success. I've even tried to add these extensions on Media Option, but nothing changed. Everytime I try to upload a rar or zip file, I get the message that no file was selected. How do I solve this problem?

**Comment by gmansillo** [comment]
Hi Romenum, I can't reproduce the issue in Simple File Manager 5.0.12.
Could it be a server/browser issue?

**Comment by Romenum** [comment]
I've tried at least in four browsers. Maybe it's the server. I'm using a shared host at Dreamhost. Thanks anyway! :)
