### ISSUE TITLE
link to website in the email notification

### ISSUE THREAD

**Issue by chiccofra** [gmansillo/simple#51]
Dear, is it possible to change the message in the email notification? Now the standard is:

_Oggetto: Nuovo documento inserito
Un nuovo documento è stato inserito nell'area download. Accedi ora per scaricarlo__

It could be nice if  "Accedi ora per scaricarlo" would be a customizable link
thanks

**Comment by gmansillo** [comment]
Of course! You can override both subject and content language string via the joomla language manager
