### ISSUE TITLE
Simple File Manager sort function

### ISSUE THREAD

**Issue by stesprea** [gmansillo/simple#52]
In Simple File Manager I have a problem in the sort function of the files from the front end.
When using the two drop-down menu at the top right to change the sort order of the documents, I go to a page whose URL is of the type ".../index.php?option=com_simplefilemanager&view=simplefilemanagers&Itemid=XXX" and it throws an error (500).
If I click "back" in the browser, "magically" page of the searched results appears, with the order willed.
The error appears to me even if I do it as Super User.
Someone can give me a tip to solve the problem?

**Comment by gmansillo** [comment]
Hi stesprea,
does it happen when you are in a subcategory?

**Comment by stesprea** [comment]
The same thing happens: Error 500



----Messaggio originale----

Da: notifications@github.com

Data: 10-feb-2017 18.38

A: "gmansillo/simplefilemanager"<simplefilemanager@noreply.github.com>

Cc: "stesprea"<stefano.spreafichi@tin.it>, "Author"<author@noreply.github.com>

Ogg: Re: [gmansillo/simplefilemanager] Simple File Manager sort function (#52)




Hi stesprea,

does it happen when you are in a subcategory?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gmansillo/simplefilemanager","title":"gmansillo/simplefilemanager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gmansillo/simplefilemanager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gmansillo in #52: Hi stesprea,\r\ndoes it happen when you are in a subcategory?"}],"action":{"name":"View Issue","url":"https://github.com/gmansillo/simplefilemanager/issues/52#issuecomment-279010931"}}}

**Comment by gmansillo** [comment]
I'm about to release v5.1.1 that doesn't have this issue so I'm going to close the issue for now.
Please open a new ticket if the described behavior should appear again.
