### ISSUE TITLE
Impostazione visibilità file su Frontend

### ISSUE THREAD

**Issue by maxsurace** [gmansillo/simple#53]
Ciao, premetto che il componente è ottimo!!!
Una domanda se effettuo il caricamento da frontend con il pulsante carica non trovo la possibilità di assegnare il gruppo/utente è corretto? Sbaglio qualche impostazione?
Sarebbe molto utile.
Grazie
Massimiliano

**Comment by gmansillo** [comment]
Hi Max,
unfortunately Joomla doesn't provide a user selection form field for frontend so I had to remove that feature. If you want to upload reserved files you have to do it from Joomla backend. This is a safe operation thanks to Joomla! 3 ACLs.
