### ISSUE TITLE
Mancata visualizzazione icone

### ISSUE THREAD

**Issue by zinisimone** [gmansillo/simple#54]
Le icone relative allo stato del file (pubblicato / non pubblicato) modifica e cancella non vengono visualizzate, rendendo molto complesso l'uso del plugin.
![immagine](https://cloud.githubusercontent.com/assets/25673436/22804910/7d6e940a-ef1b-11e6-9b08-ef5518b4340d.png)

Cliccando sui link relatve all'ordinamento o alla paginazione si viene mandati alla pagina di errore 500

![immagine](https://cloud.githubusercontent.com/assets/25673436/22805017/e3dd19aa-ef1b-11e6-85c2-278758617c96.png)

**Comment by gmansillo** [comment]
Hi,
can you see icons if you use the default joomla frontend template?
Is your frontend template based on bootstrap 2.3.2?

**Comment by gmansillo** [comment]
Closed for lack of response.
Similar issue: #64
