### ISSUE TITLE
creare aree riservate per ogni utente 

### ISSUE THREAD

**Issue by VeronicaGordini** [gmansillo/simple#55]
Ciao,
inanzitutto complimenti per il componente che hai sviluppato.

Avrei necessità di creare aree download per ogni utente registrato; se uso ACL di joomla devo crare livelli di accesso per ogni utente e creare una voce di menù per l'area download di ogni utente, dire un po' macchinose se si hanno tanti utenti.

Con il tuo componente c'è la possibilità di creare tale automatismo? Cioè  creare in automatico un'area riservata dove mettrere dei documenti per ogni utente e appena un utente si registra si trova nella sua area. Grazie.

**Comment by gmansillo** [comment]
Ciao Veronica,
grazie per i complimenti! Spero che tu abbia già avuto modo di testare Simple per sperimentare la sua semplicità d'uso. Qualora non lo avessi ancora fatto, ti suggerisco di farlo al più presto: scoprirai che Simple è stato pensato proprio per esigenze come quella che stai avendo tu in questo momento. È veramente seccante dover creare un livello di accesso per ogni singolo utente, perché non lasciare che sia il componente stesso ad occuparsene? Simple gestisce questo aspetto per te e ti consente di avere una unica area personale (eventualmente organizzata in sottocategorie) che viene generata dinamicamente in modo diverso per ogni singolo utente.

Se dovessi avere bisogno di aiuto, non esitare a scrivere :-)

**Comment by VeronicaGordini** [comment]
Buongiorno Giovanna,
grazie per la risposta, sì ho già utilizzato il componente in un sito in cui dovevo creare un semplice area di download per utenti public e qui il problema non c'era.

In un altro sito come accennavo precedentemente devo creare un'area download per ogni utente registrato, perché devono avere la possibilità di scaricare attestati personalizzati.

Ho fatto dei tentativi con il tuo componente, ma senza risultati per la mia problematica, forse sbaglio qualche impostazione, chiedo se gentilmente mi potresti scrivere qualche passaggio in modo tale quando un utente si registra vede la proprio area download, grazie ancora. Buon lavoro.

**Comment by VeronicaGordini** [comment]
Scusami, ho scritto Giovanna, invece che Giovanni...

**Comment by gmansillo** [comment]
Quando crei un nuovo documento, nella tab "**impostazioni visibilità file**" seleziona **Singolo utente** e subito sotto seleziona l'utente che dovrà visualizzare il file:

 ![image](https://cloud.githubusercontent.com/assets/11967003/25423241/36c0bdc4-2a64-11e7-8f81-69306af6b957.png)

**Comment by altermedia77** [comment]
Grazie, verificato funziona.


Il 26/04/2017 09:40, Giovanni ha scritto:
