### ISSUE TITLE
Not Secured with .htaccess as stated in the JED 

### ISSUE THREAD

**Issue by ChasLarge** [gmansillo/simple#56]
You state:

**_Security first

In Simple File Manager every file is protected by external access via an .htaccess file and is stored in a random-generated path in order to increase storage security._**

But there are no .htaccess files placed anywhere in the secure directories. I set up a login test file to test. Yes the J! ACL prevents access to the page where the link is but the link itself is insecure. Searching for the file finds it. 

My file is found easily so this security statement is blatantly wrong.

If it had worked, then sure, I would have paid for it.

Chas Large

**Comment by gmansillo** [comment]
Hi @ChasLarge,
thank you for reporting the issue. Clearly this is a bug of the latest version (previous versions had that file). I'm going to release the security fix very soon, in the meanwhile you can manually create an .htaccess file with following content in administrator/components/com_simplefilemanger/uploads:

`Options -Indexes`
`Require all denied`

or if you are using an older version of Apache (i.e. 2.2):

`Options -Indexes`
`Order deny,allow`

Hope it helps

**Comment by gmansillo** [comment]
Ok, it should have been fixed since version 5.1.1 (soon available).

I close the issue for now.
