### ISSUE TITLE
order in simple file manager

### ISSUE THREAD

**Issue by georgeda** [gmansillo/simple#57]
I have a little problem...i need to order some simple file manager documents „oldest first” and i can find where can i make changes that it work...Can you help me please?

**Comment by gmansillo** [comment]
Hi,
can you describe the issue you are encountering? Is it the same as #52 ?

**Comment by georgeda** [comment]
Is not like 52...I work as admin on a site...i have uploaded some documents and i want that my last document added to be seen on the site as first document on the page...simple file manager sort for me all document from A to Z... what i want is that when i post a new document, that document must stay firs on the page and not the last one...thank you...

And anouther problem is that:  
When I am on a categori with multiple pages in frontend, that means on the site, when i go to the second page, simple file manager show me again all categories...
you can try it here: http://www.primariababadag.ro/index.php/idip?view=simplefilemanagers
each category has multiple pages of documents...when i navigate among pages, simple file manager send me every time to the category, and that is not so comfortable...
can you please help me ?

**Comment by georgeda** [comment]
Can you help me please with my problem?

**Comment by gmansillo** [comment]
Hi georgeda,
you were right: there was an issue in sorting subcategories. I fixed it in v5.1.1 that I'll release soon.

Thanks for your patience.
