### ISSUE TITLE
upload da backend

### ISSUE THREAD

**Issue by ludusmagnus** [gmansillo/simple#59]
Ciao,

ho installato il tuo componente, ma - provando a fare l'upload di un file da backend - mi dà "Error 500".
Ho dimenticato di impostare qualcosa?
Grazie,

Alessandro.

**Comment by gmansillo** [comment]
Ciao Alessandro,
qual'è la versione di Joomla che utilizzi?

**Comment by ludusmagnus** [comment]
Joomla 3.5.1

**Comment by gmansillo** [comment]
Ho testato il caricamento di un file sulla 3.6.5 e 3.7.0 senza problemi, proverò a fare un caricamento anche su una 3.5.1. Nel frattempo non è che hai attiva qualche estensione/plugin di sicurezza che blocca il componente?
![image](https://cloud.githubusercontent.com/assets/11967003/25997361/fcc07730-371b-11e7-9133-387401b2c0ee.png)
![image](https://cloud.githubusercontent.com/assets/11967003/25997272/c1a889f8-371b-11e7-93fe-a937cd6d472a.png)

**Comment by ludusmagnus** [comment]
Ciao Giovanni, no, non ci sono oggetti bloccanti...
O almeno, non che io sappia.
Altrimenti, possiamo provare ad aggiornare Joomla.

Alessandro. 


Da: "Giovanni" notifications@github.com
A: "gmansillo/simplefilemanager" simplefilemanager@noreply.github.com
Cc: "ludusmagnus" info@ludusmagnusroma.it,"Author" author@noreply.github.com
Data: Fri, 12 May 2017 05:05:22 -0700
Oggetto: Re: [gmansillo/simplefilemanager] upload da backend (#59)


Ho testato il caricamento di un file sulla 3.6.5 e 3.7.0 senza problemi, proverò a fare un caricamento anche su una 3.5.1. Nel frattempo non è che hai attiva qualche estensione/plugin di sicurezza che blocca il componente?

**Comment by gmansillo** [comment]
Potrebbe essere una buona idea arrivare almeno alla 3.6, anche se non ricordo ci fossero incompatibilità con la 3.5. 
Il log degli errori di php ti da qualche informazione che può esserci utile?

**Comment by gmansillo** [comment]
Chiudo per mancanza di informazioni :-(

**Comment by ludusmagnus** [comment]
Giovanni,

ho aggiornato Joomla (3.7.2), ma continua a non funzionare.
Qualche idea? 


Da: "Giovanni" notifications@github.com
A: "gmansillo/simplefilemanager" simplefilemanager@noreply.github.com
Cc: "ludusmagnus" info@ludusmagnusroma.it,"Author" author@noreply.github.com
Data: Mon, 29 May 2017 13:24:47 -0700
Oggetto: Re: [gmansillo/simplefilemanager] upload da backend (#59)


Closed #59.

**Comment by gmansillo** [comment]
Non riesco a ricreare il problema e lo stesso non mi è stato segnalato fin'ora da altri utenti quindi credo che sia relativo alla tua configurazione di Joomla. Controlla che il log errori di php o la stessa pagina di errore non ti diano qualche info in più.
