### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by georgeda** [gmansillo/simple#60]
I work as admin on a site...i have uploaded some documents and i want that my last document added to be seen on the site as first document on the page...simple file manager sort for me all document from A to Z... what i want is that when i post a new document, that document must stay firs on the page and not the last one...thank you...

And anouther problem is that:
When I am on a categori with multiple pages in frontend, that means on the site, when i go to the second page, simple file manager show me again all categories...
you can try it here: http://www.primariababadag.ro/index.php/idip?view=simplefilemanagers
each category has multiple pages of documents...when i navigate among pages, simple file manager send me every time to the category, and that is not so comfortable...
can you please help me ?

**Comment by gmansillo** [comment]
Hi,
which version of Simple are you using? And which version of Joomla?

**Comment by georgeda** [comment]
simple file manager 5.0.13
Joomla 3.6.3

**Comment by gmansillo** [comment]
I just made a test. This would be the order if documents were sorted by name:
![image](https://cloud.githubusercontent.com/assets/11967003/26077632/068fe66c-39bd-11e7-9ad3-4230a0666c19.png)
I checked that in menu item options sort order is set to "Creation date":
![image](https://cloud.githubusercontent.com/assets/11967003/26077692/3c5c9fba-39bd-11e7-86da-f36c04cfd122.png)
And this is the result:
![image](https://cloud.githubusercontent.com/assets/11967003/26077730/6add1a36-39bd-11e7-88b8-01a2cf9b2159.png)
So i think there's no problem with it 😉 

I can't understand you second request. Can you make me an example?

**Comment by gmansillo** [comment]
Hi,
did you try my solution?

**Comment by gmansillo** [comment]
About the second issue, do you mean that when you change the sorting field you are redirect to the main category? In this case this is a bug and should be clearly fixed!
Thanks for reporting it

**Comment by gmansillo** [comment]
Ok, sorting issue has been fixed since version 5.1.1 (soon available).

I'm going to close the issue for lack of response from the owner.
