### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by ChasLarge** [gmansillo/simple#61]
Can you put user ID or USERNAME of user downloading file into table for simple file manager. I use ARI Datatables to pull data from main dB for analysis and it would be good to see which user downloaded file.

Kind regards
Chas.

PS ,htaccess tip you sent worked. Have sent donation.

**Comment by gmansillo** [comment]
Thank you ChasLarge,
I think that this would be a good idea. I'll try to add to the nex release a secondary table with:

- user id
- document id 
- download time 
- (client ip address?)

Than if you need further data you can make a left join with user and document table.

**Comment by ChasLarge** [comment]
Dear Giovanni,

 

That would be excellent. Thank you.

 

BTW, is it possible to allow users to UPLOAD files? I could not find the documentation for this.

 

Regards

Chas

 

 <http://www.chas-large.co.uk/> 
Chas Large - Web Design, Management & Electronic Documentation.

07730 538 697 www.chas-large.co.uk <http://www.chas-large.co.uk>

**Comment by gmansillo** [comment]
Hi Charles,
your request has been added to the source code of 5.1.4. You will find this feature in the next release. 
By default the feature is disabled. You will be able to enable it from component global settings.

Thank you for your suggestion!
