### ISSUE TITLE
Problema abbinamento documento alla categoria

### ISSUE THREAD

**Issue by francescscos** [gmansillo/simple#62]
Buongiorno Giovanni,
ho aggiornato Joomla 3.7 e non ho la possibilità di collegare il documento alla singola categoria nella maschera di caricamento.
In pratica quando faccio nuovo caricamento, vado a selezionare la tendina della categoria (a destra) e visualizzo solo una categoria mentre prima dell'aggiornamento le visualizzavo tutte.
Mi puoi aiutare, adesso come adesso la mia area riservata è inutilizzabile,
grazie

**Comment by gmansillo** [comment]
Ciao Francesco, quale versione di Simple stai utilizzando?

**Comment by francescscos** [comment]
Ho ottenuto la versione senza back link a fine gennaio. Da dove vedo la versione?

**Comment by francescscos** [comment]
Scusa, ho verificato, è la versione 5.0.12P

**Comment by francescscos** [comment]
Buongiorno Giovanni, mi puoi dare aiuto? Grazie.

**Comment by gmansillo** [comment]
Ciao Francesco,
che versione di Joomla! avevi prima dell'aggiornamento?

Poichè non riscontro l'errore che segnali sulla 3.7, vorrei provare a ricreare il problema partendo dalle tua stessa situazione.

**Comment by francescscos** [comment]
Come faccio a vedere quale era la versione precedente?

**Comment by francescscos** [comment]
Indico passo passo come operavo fino a qualche giorno fa:
per gestire SFM procedo cosi:
-	Creo l’utente;
-	Creo un gruppo (es.: FATTURE)
-	Poi creo il livello di accesso con lo stesso nome del gruppo (FATTURE)
-	Creo la categoria (FATTURA)
Entro nella gestione dell’utente e nell’albero “guppi e permessi utente” fleggo su “Registred” e “Fatture”;
quando carico una fattura apro la tendina della categoria sulla destra e non ho la possibilità di selezionare “FATTURE”.
Ho chiesto info e delucidazioni anche al mio HOSTING e mi dicono che gli aggiornamenti sono OK, potrebbe essere incompatibilità di SFM con l’ultima versione di Joomla

**Comment by gmansillo** [comment]
Quando hai effettuato l'aggiornamento automatico dovresti aver visualizzato una pagina simile a questa:
![image](https://cloud.githubusercontent.com/assets/11967003/26149703/8f766368-3afb-11e7-9ad8-5241c3a9736f.png)
qui è annotata la versione di partenza del cms prima dell'aggiornamento. Non so se esistano altri modi per conoscere la vecchia versione di Joomla.

Questo è quello che vedo io sulla 3.7:
![image](https://cloud.githubusercontent.com/assets/11967003/26150181/8ca70bc2-3afd-11e7-8590-53264d94df68.png)
Se non riesco a ricreare il problema, non saprei come aiutarti. L'alternativa potrebbe essere attendere il rilascio della nuova versione ma potrebbero sorgere complicazioni in quanto è leggermente cambiata la logica di funzionamento (sono state introdotte le assegnazioni multiple, ecc..)

**Comment by francescscos** [comment]
Ho chiesto al mio HOSTING se possono verificare loro ed attendo risposta ma sono certo che con Joomla 3.6.4 tutto funzionava bene.
Attendo tue, grazie

**Comment by gmansillo** [comment]
Credo che l'hosting non abbia responsabilità in questo caso, il problema è da cercare altrove. Prova intanto ad aggiornare alla 3.7 1

**Comment by francescscos** [comment]
Buongiorno Giovanni, ho appena aggiornato joomla alla versione 3.7 1 ed il problema persiste: nella tendina della categoria non riesco a visualizzarle tutte. Helpl me!

**Comment by francescscos** [comment]
Ho avuto risposta dal mio HOSTING circa la versione Joomla installata prima della 3.7 e mi riferisce quanto segue:  "la versione installata precedentemente sembra essere la 3.6.5".
Attendo tue indicazioni, grazie

**Comment by gmansillo** [comment]
Faccio un upgrade dalla 3.6.5 alla 3.7 e verifico cosa accade

**Comment by gmansillo** [comment]
Aggiornato correttamente da 3.6.5 a 3.71
![image](https://cloud.githubusercontent.com/assets/11967003/26236989/78175730-3c73-11e7-9b39-9a9676e7f835.png)

E' ancora possibile seleionare le categorie:
![image](https://cloud.githubusercontent.com/assets/11967003/26237026/a86eeaba-3c73-11e7-9a4b-f06c654b738e.png)

E' possibile che riscontri lo stesso prolema anche con altri componenti?

**Comment by gmansillo** [comment]
L'elenco delle categorie disponibili non è gestito da Simple ma dal core di Joomla!.

Puoi verificare che nella tabella `#__categories` esistano ancora tutte le categorie dell'estensione com_simplefilemanager? In alternativa puoi visualizzarle dal menu Estensioni > Simple File Manager > Categorie

**Comment by gmansillo** [comment]
Sembra che dopo l'upgrade alla 3.7 altri utenti abbiano avuto lo stesso problema con altre estensioni. Probabilmente si tratta di un bug introdotto con la nuova famiglia di aggiornamenti di Joomla!. 
Qui c'è una possibile soluzione (da verificare): https://forum.joomla.org/viewtopic.php?t=949942

**Comment by gmansillo** [comment]
Verificato da un altro utente: cambiando i gruppi di appartenenza del superadmin, il problema viene risolto. 
Il bug è nell'aggiornamento a Joomla 3.7 e colpisce molte estensioni esterne. Chiudo la segnalazione
