### ISSUE TITLE
Updating doesn't work

### ISSUE THREAD

**Issue by pdvmedia** [gmansillo/simple#63]
hello all,

When  I try to update the filemanager it doesn't work. I updated my complete website to Joomla 3.7 and tried updating the filemanager, it doesn't work. I also tried to reinstall (without unistalling) the component, but I got the error in the attachement. 
![simple file manager](https://cloud.githubusercontent.com/assets/19713580/26176628/116e70b2-3b57-11e7-8f6b-65903ccec740.JPG)

I have version 4.1.0, and I want to update to 5.0.13. For now, I put a backup of the complete website back on the server.

What can be the problem?

Thanks a lot in advance,

Pieter de Visser

**Comment by gmansillo** [comment]
Hi,
major release 4 and 5 are not compatibile: il you want to use v. 5.x you
need to install it from scratch.
Please restore a backup of the old version: I'm available to try to upgrade
to 5.x manually with you

Il 17 mag 2017 11:20 PM, "pdvmedia" <notifications@github.com> ha scritto:

**Comment by pdvmedia** [comment]
Hello gmansillo,

Thanks a lot for fast response. On my website, I have now version 4.1.0.

My questions:
1. Does this version also run with joomla 3.7?
2. Is it necessary to update to version 5.x for safety?
3. If 2 is 'Yes': Now I have a website with data. When I unistall version 4.1.0 and install version 5.0, is it necessay to fill it again with documents or does the new version that together with installing?

Thanks a lot,

Pieter de Visser

**Comment by gmansillo** [comment]
Ok
so I assume that you have a working backup for any possible disaster ( 😨 )

Can you confirm me the structure of your #__simplefilemanager table attaching a dump of some rows of that table or a screenshot of any db IDE?

**Comment by pdvmedia** [comment]
Hello Giovanni,

Yes I have.

In the attachment you find an export of the table. The table is to big to make a screenshot

[qwg4s_simplefilemanager.zip](https://github.com/gmansillo/simplefilemanager/files/1011793/qwg4s_simplefilemanager.zip)

Thanks a lot!

**Comment by gmansillo** [comment]
Sorry, I didn't notice your questions.

Yes, all versions 5.x also run with joomla 3.7.
No, there is no reason for upgrading from 4.x to 5.x if you don't require new features. 4.x is mature enough (while 5.x is not 😢 ).

**Comment by gmansillo** [comment]
What I would like to try with you is a complete upgrade process from 4.1 to 5.1.0 (a version that i didn't release yet but with some new features you'll surely like 😄 )

### We start creating required tables launching the following two scripts:
```
create table jos_simplefilemanager_group_documents
(
	id int not null auto_increment primary key,
	group_id int not null,
	document_id int not null
);

create table jos_simplefilemanager_user_documents
(
	id int not null auto_increment primary key,
	user_id int not null,
	document_id int not null
);
```
Please notice: `jos ` should be replaced with your current joomla table's prefix!

### Then we populate new tables with data from the main table:
```
INSERT IGNORE INTO `#__simplefilemanager_user_documents` (user_id, document_id)
  SELECT
    reserved_user,
    id
  FROM `#__simplefilemanager`
  WHERE reserved_user > 0;

UPDATE `#__simplefilemanager`
SET `reserved_user` = 3 WHERE `reserved_user` > 0;
```
### Now we have to update the table schema:
```ALTER TABLE jos_simplefilemanager
ADD COLUMN license varchar(250) null,
ADD COLUMN license_link varchar(250) null,
ADD COLUMN author int null,
ADD COLUMN version varchar(250) null,
ADD COLUMN notes text null,
ADD COLUMN md5hash varchar(250) null,
ADD COLUMN visibility tinyint(1) default '1' not null;
```
At this point we have an updated database schema and we should be ready for uploading updated files from Simple 5.1.0.

**Comment by gmansillo** [comment]
Hi,
did you try the procedure?

**Comment by pdvmedia** [comment]
Hello,

Excuse me for the late reaction. I didn't do that, because we don't need more functionality..

Thanks a lot,

PDV

**Comment by gmansillo** [comment]
You're welcome
