### ISSUE TITLE
Visualizzazione layout list da smartphone

### ISSUE THREAD

**Issue by VeronicaGordini** [gmansillo/simple#64]
![screen_1](https://cloud.githubusercontent.com/assets/16699106/26441265/1b954384-4130-11e7-871c-fb3cf5a87263.PNG)
![screen_2](https://cloud.githubusercontent.com/assets/16699106/26441264/1b91c95c-4130-11e7-9439-98ba54d3c290.PNG)

Buongiorno,
inoltro due screen che riporta il layout da smartphone del componente in due template diversi di Joomla; 

**screen_2** template standard installazione joomla, la visualizzazione segue le dimensioni delle schermo
**screen_1** template acquistato, quando la risoluzione dello schermo si rimpicciolisce sotto i 768px icona del tipo di documento sparisce, e il testo va a capo, (mentre ho nascosto volutamente i button dell'ordinamento e visualizzazione). 

Riporto anche file screen con visualizzazione css tramite firebug
![screen_1_firebug](https://cloud.githubusercontent.com/assets/16699106/26442117/775d15ea-4133-11e7-8d3b-bc15de18f301.jpg)
![screen_2_firebug](https://cloud.githubusercontent.com/assets/16699106/26442118/7762a00a-4133-11e7-8246-8363b76c10c8.jpg)
Dallo **screen_2_firebug** si nota che firebug evidenzia il form, mentre nello **screen_1_firebug** non viene evidenziato il form, come se non seguisse più il layout del template.

Chiedo da cosa potrebbe dipendere, non ci sono regole css per smartphone che rendano una tale visualizzazione.

Grazie fin da ora per una risposta. Buona lavoro. 
Veronica

**Comment by gmansillo** [comment]
Ciao,
dovresti mostrami lo stile applicato alle icone andandole a selezionare espandendo il nodo "ul#sfm-category-list > li#sfm-list-item-x > ecc...". Una volta trovato il problema si può risolvere con una semplice override della vista.
