### ISSUE TITLE
SQL Syntax Error at line 15

### ISSUE THREAD

**Issue by JefPattat** [gmansillo/simple#65]
Hello,
I get the syntax error below when I open a category list from the menu only when logged in.
All is set to public and works perfect when logged out.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) AS a LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__users ' at line 15 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) AS a LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__users ' at line 15

**Comment by gmansillo** [comment]
Hi,
wich version of Simple are you using?

**Comment by JefPattat** [comment]
Hello,


I'm using v5.1.0 running on Joomla  3.7.2

Supposing this is the latest version?

[cid:a5ed973f-0404-46bc-b06b-40078b6ec769]
I've downloaded the installer from your website earlier this week.

Regards,
Jef

________________________________

**Comment by alkemica** [comment]
Hi, i have the same problem. Latest Simple file manager version and joomla 3.7.2 + php 5.6.30.

**Comment by gmansillo** [comment]
There may be a mistake: latest version is 5.0.13

Anyway I'm going to check this issue

**Comment by alkemica** [comment]
Yes. It is the version  that I installed yesterday.

Il 01 Giu 2017 2:32 PM, "Giovanni" <notifications@github.com> ha scritto:

**Comment by JefPattat** [comment]
My server is using same php version: 5.6.30

The only place I know to check the version is in Extentions > Manage.
When I filter "Simple" it shows version 5.1.0, date Sept 2014.

Probably something wrong in "simplefilemanager.xml"?
`<name>com_simplefilemanager</name>
<author>Giovanni Mansillo</author>
<creationDate>Sep 2014</creationDate>
<copyright>(C) 2014 Giovanni Mansillo. All rights reserved.</copyright>
<license>GNU General Public License version 3 or later</license>
<authorEmail>support@simplefilemanager.eu</authorEmail>
<authorUrl>http://www.simplefilemanager.eu</authorUrl>
<version>5.1.0</version>`

**Comment by alkemica** [comment]
I confirm that i installed the latest version directly downloaded from the site and there is the problem when logged in.

**Comment by gmansillo** [comment]
I'm going to release an update (ideally tomorrow). Please let me know if it fixes the issues. I'm doing my best to improve the extension.

**Comment by gmansillo** [comment]
I just published the release 5.1.1
I purposely skipped version number 5.1.0 because otherwise JefPattat wouldn't get the update.

I'm going to close the issue and I invite you to open another one in case you'll encounter the issue again (or similar issues!).

Thank you for your support and patience.
