### ISSUE TITLE
Access error when you are logged

### ISSUE THREAD

**Issue by alkemica** [gmansillo/simple#66]
Hi, i try with the 5.1.1 version but the problem persist ([gmansillo/simplefilemanager] SQL Syntax Error at line 15 (#65)).
When an user is logged and click on the simple file manager page, you see this:

0 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) AS a LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__user' at line 15 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) AS a LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__user' at line 15

**Comment by gmansillo** [comment]
Hi alkemica,
i've found the issue. I wasn't able to find it before because the issue happens only when you log with an user without admin privileges. I'm going to fix it as soon as possible.

Thank you for reporting it.

**Comment by gmansillo** [comment]
Hi @alkemica, please try the release 5.1.2.

Thanks

**Comment by gmansillo** [comment]
Issue has been fixed in Simple 5.1.2.

I'm going to close the issue. Please reopen this ticket if you think that this bug hasn't been fixed properly.
Regards
