### ISSUE TITLE
Document not showing when Access limited to Selected groups

### ISSUE THREAD

**Issue by JefPattat** [gmansillo/simple#68]
Hi,

When I set the Category Access to "Registered" and Document Access to "Selected groups" with a self created user group added to "Visibility groups", the document doesn't show up.

What am I doing wrong?

**Comment by gmansillo** [comment]
Hi, it could be a bug.
I'm trying to reproduce the issue. Thank you for reporting it

**Comment by gmansillo** [comment]
I just checked that this doesn't happen in version 5.1.3. I just pray you to wait for this update to solve the issue.

Thank you for reporting it
