### ISSUE TITLE
Category Drop-Down list empty

### ISSUE THREAD

**Issue by f-m-p** [gmansillo/simple#69]
Category Drop-Down list is empty although several categories are in th category-inventory.
Jommla Version: 3.7.3
tested with SimpleFileManager 5.0.9 and 5.0.12  
![simplefilemanager_issue](https://user-images.githubusercontent.com/30185126/28251339-4f221104-6a7b-11e7-930c-6d4c7f12b35a.png)

**Comment by gmansillo** [comment]
Hi,
If you just upgrade to Joomla 3.7.x, please note that there's a bug in the upgrade procedure: at.this point you have to re-assign administrator's permissions in order to see categories listed again

**Comment by f-m-p** [comment]
Hello,
Yes, this seems to be the reason. I created a new user-account and added it to several groups: Superuser, Manager, Administrator, etc..
With this user-account it was possible to see the categories. 

So I guess this issue could be closed.
