### ISSUE TITLE
Version on manifest

### ISSUE THREAD

**Issue by fnotti** [gmansillo/simple#71]
Hi,

Extension Update manages tells that actual version is 5.0.12 and newer is 5.1.2 all the time since months.

<version>**5.1.2**</version>
<downloads>
<downloadurl type="full" format="zip">
https://github.com/gmansillo/simplefilemanager/releases/download/5.1.2/com_simplefilemanager-**5.0.12**.zip

Regards.-

**Comment by gmansillo** [comment]
Hi,
thank you for reporting this. It should have been caused by a wrong package uploaded on github.
It should be ok now.

Please reopen this issue if you get the problem again!
