### ISSUE TITLE
simple file manager component disappeared

### ISSUE THREAD

**Issue by lopyno** [gmansillo/simple#72]
Hallo,
I have a trouble with simple file manager. In the component menu, simple file manager disappeared after last extension update in a website made with joomla! ver. 3.7.5.
Please can you help me to solve the problem?
Any suggestion would be helpfull.
Thanks.

**Comment by gmansillo** [comment]
Hi,
can you find it under **Extensions** > **Documents** ?

**Comment by lopyno** [comment]
Hi,
I can find documents and categories in that path. This is a good thing, trans. I can't understand why I can't find Simple file manager menù under extensions, to access the program, anyway I can add new file using the path you duggedted to me.
Thank you so much
Bye

Inviato da iPhone

Il giorno 06 set 2017, alle ore 10:09, Giovanni <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi,
can you find it under Extensions > Documents ?

**Comment by gmansillo** [comment]
Hi
I totally agree with you and I understand your disappointment. When I decided to change the path of the component i wanted to make it more intuitive and more similar to core extensions. It's just that I forgot to alert users 😖 

I hope that this topic will be useful for other users.
