### ISSUE TITLE
after the update of joomla and componte no longer sees any file

### ISSUE THREAD

**Issue by fanny00** [gmansillo/simple#73]
hi

after the update of joomla and componte no longer sees any file 
Joomla! 3.7.5  
com_simplefilemanager-5.1.2

**Comment by Filotea** [comment]
I also have the same problem ....

**Comment by gmansillo** [comment]
Hi,
I'm already doing a research about the causes. Which version of joomla/simple was you using before the update?

**Comment by fanny00** [comment]
the previous one

thanks!

**Comment by Filotea** [comment]
I do not remember the previous one version.
I also note the following errors:
- no longer sends email when a new document is inserted
- there is no longer the "Save and New" button when you insert a new document
- when you modify an existing document and check the "Resend notification email" entry, the system as an error: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3


we urgently need your help!!

**Comment by gmansillo** [comment]
@Filotea i'll verify the other issues.

About the documents, can you see them in admin backend?

**Comment by gmansillo** [comment]
Hi @Filotea and @fanny00 ,
if you can't see files in frontend but these are listed  in backend, there could be an issue in db conversion query. I'd suggest you to restore a db/file backup and to execute the update procedure again, removing the `update ..... set reserved_group = NULL` and `update ..... set reserved_user = NULL` lines from admin/sql/update/.....  files

**Comment by Filotea** [comment]
I have now hung up the documents one by one and for each user profile.
At this point I do not think it's okay to remove the current update because I might lose the job again.
What do you suggest me?
Will there be future upgrades that will solve everything?

**Comment by gmansillo** [comment]
Once you have updated to 5.1.2, you don't need to update again to the same version so that query won't be executed again and you won't lost data.  I only suggest you to update your Joomla! website in a sandbox installation (or to save a backup for recovering data) in order to prevent issues like this.

I'm sorry for the inconvenience 😢
