### ISSUE TITLE
Simple File Manager 

### ISSUE THREAD

**Issue by lsavino59** [gmansillo/simple#74]
Salve,
ho scaricato e installato Simple File Manager, un'estensione molto utile e semplice da utilizzare.
Volevo sapere se c'era un modo per apportare una piccola modifica sulla data.
Devo creare un'area dove gestisco la rassegna stampa, dove per ogni articolo carico un pdf, però ho bisogno di poter editare la data di caricamento, in modo da farla coincidere con la data di pubblicazione dell'articolo.
Dovendo caricare un numero elevato di articoli, pubblicati nell'ultimo anno, non posso metterli tutti con la stessa data, devo poterli ordinare in modo corretto.

Grazie e buon lavoro

**Comment by gmansillo** [comment]
Ciao @lsavino59,
attualmente non è possibile cambiare la data di caricamento ma mi sembra un'ottima idea dare la possibilità all'amministratore di selezionarne una a scelta. Applicherò la modifica al prossimo aggiornamento.

Grazie per il suggerimento

**Comment by lsavino59** [comment]
Grazie per la disponibilità.

**Comment by gmansillo** [comment]
La funzionalità sarà disponibile a partire dalla versione 5.1.3
