### ISSUE TITLE
Problemi installazione Simple file Manager

### ISSUE THREAD

**Issue by rostrato** [gmansillo/simple#75]
Salve,
ho scaricato il componenete senza dare ancora un contributo per l'autore e installato su joomla 3.5.0
Dopo e' venuto fuori il messaggio che il componente e' stato installato correttamente ma nel backend di joomla non lo vedo nella lista Componenti.
Dove sbaglio?
Grazie in anticipo.
Domenico

**Comment by gmansillo** [comment]
Ciao Domenico,
a partire dalla versione 5.0.1 trovi Simple sotto componenti -> "Documenti"

**Comment by rostrato** [comment]
Grazie Giovanni. Tutto ok.....o quasi
Mi sto incasinando con i permessi Help!
Allora da front end devo avere la possibilità di uplodare in remoto i file pdf che sarebbe degli atti notarili e fin qui ci sono arrivato creando una cartella "Atti Stipulati" con i permessi di visualizzazione voce di menu' solo al super user.
Poi dovrei avere sempre una voce di menu "I Miei Atti" visibile ai soli utenti registrati. Da qui una volta che l'utente registrato pippo pluto, dopo essersi loggato, potrà vedere tutte le pratiche a lui riguardanti.
A prova fatta l'utente diverso da pippo pluto vede tutti i documenti caricati di tutti.
Chiedo gentilmente aiuto.
Grazie

**Comment by rostrato** [comment]
Risolto. Grazie
Ovviamente era tutto sui permessi.

**Comment by gmansillo** [comment]
Ciao @rostrato ,
grazie per la segnalazione. A partire dalla versione 5.1.13 ho ottimizzato la query che filtra i documenti da visualizzare, riducendo al minimo la possibilità che vi siano errori nel filtraggio.

Giovanni
