### ISSUE TITLE
Problema invio mail

### ISSUE THREAD

**Issue by rostrato** [gmansillo/simple#76]
Salve
Testando a pieno il componente e facendo una prova di invio mail per il caricamento avvenuto di un file viene fuori lato bachend questa stringa di errore:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3 SQL=SELECT u.user_id FROM #__simplefilemanager_user_documents WHERE a.document_id =
E la mail non arriva. Come posso risolvere?
Grazie

**Comment by gmansillo** [comment]
Ciao, è un bug che mi hanno segnalato e che risolverò nel prossimo aggiornamento

**Comment by rostrato** [comment]
Ok. come posso sapere quando vi sarà la possibilità di uplodare la nuova versione?
Grazie

**Comment by rostrato** [comment]
MI permetto col dire che potrebbe essere interessante avere anche la funzione di invio mail del documento caricato per quel cliente particolare e nella mail che venga riportato il codice MD5 generato di modo che il cliente stesso, in una sezione apposita, inserisca il codice per fare il download.

**Comment by gmansillo** [comment]
Ho corretto e migliorato la funzionalità di invio mail a partire dalla versione 5.1.3 aggiungendo la possibilità di inserire nel testo dell'email le informazioni sull'utente e sul documento tramite tag:

`Benvenuto {user.username}, è disponibile un nuovo documento con firma: {document.md5_hash}.`

La nuova versione sarà disponibile appena avrò corretto un numero sufficiente di bug, ma comunque a breve.

**Comment by gmansillo** [comment]
Ovviamente grazie per la segnalazione e per il suggerimento! ☺️
