### ISSUE TITLE
Campo seleziona utente

### ISSUE THREAD

**Issue by rostrato** [gmansillo/simple#77]
Salve
Ho installato il componente e ho creato una voce di menù per L upload dei file da front end riservata solo al super user. 
Facendo una prova e impostando che quel determinato file deve essere solo per il singolo utente e scegliendolo tra quelli già registrati viene fuori il messaggio che è andato tutto a buon fine. Da un controllo da backend  entrando nel file in questione si vede che e stato impostato singolo utente ma non all'utente specificato da front and. Come posso risolvere  tale problematica ?  Urge finire lavoro commissionatomi. Grazie

**Comment by gmansillo** [comment]
Puoi postare screenshot che mostra la differenza tra front e backend?

**Comment by rostrato** [comment]
[Nuovo Documento di Microsoft Word (4).docx](https://github.com/gmansillo/simple/files/1344282/Nuovo.Documento.di.Microsoft.Word.4.docx)
Certo. Scrren 1 messaggio verde tutto ok.
Screen2 - freccia rossa i campi non contengono niente (Visibilità singolo utente e poi quale utente tra i tanti) da backend.
Se poi dal Backend inserisco nuovamente Singolo Utente e a quale utente appartiene il file e salvo, tutto viene memorizzato correttamente.

**Comment by gmansillo** [comment]
Ciao @rostrato,
credo che il problema riguardi il frontend in quanto nella prima screenshot vedo che subito dopo il salvataggio l'impostazione visibilità è ancora su "Pubblico":

<img width="704" alt="smartselectimage_2017-10-05-08-43-28" src="https://user-images.githubusercontent.com/11967003/31214291-e6c9f558-a9aa-11e7-99ef-ef8e96da5b78.png">

Per quanto riguarda gli utenti selezionati non ho visto cosa è successo in quanto quella parte non è entrata nella screenshot.

Ad ogni modo, poiché il caricamento da frontend è una funzionalità relativamente nuova, non ho ancora un quadro chiaro di quali sono tutte le cose che non funzionano e quindi non l'ho ancora rivista. Ti prego nell'attesa di fare riferimento al backend.

Grazie per la tua segnalazione.

**Comment by gmansillo** [comment]
Ho fatto qualche modifica anche al frontend. Se lo desideri, puoi testare le modifiche in anteprima scaricando il pacchetto dall'issue #79 

Fammi sapere se il problema è stato risolto!

Grazie

**Comment by rostrato** [comment]
Caro Giovanni,
ho fatto alcune prove con
https://github.com/gmansillo/simple/files/1382159/com_simplefilemanager-5.1.3-rev3.zip
ma niente da fare.
Se opero invece da bkend e' tutto ok.
Soluzioni?
Grazie

2017-10-09 16:53 GMT+02:00 Giovanni <notifications@github.com>:

**Comment by gmansillo** [comment]
Nella 5.1.4 ho riscritto completamente la parte di upload eliminando tutti i campi superflui. 
NB: non è possibile effettuare un aggiornamento automatico dalle versioni precedenti ma rilascerò appena possibile una guida per la migrazione manuale.
