### ISSUE TITLE
How can I change the order of the shown subcategories?

### ISSUE THREAD

**Issue by IrmaBE** [gmansillo/simple#78]
Hi, 
I use your tool to safe music files for my choir in a joomla website.
I would like to have the subcategories of "music" to be orded by title alfabetically.
How do I do this?
Thanks in advance for your help!
Cheers,
Irma

**Comment by IrmaBE** [comment]
I found it already.. I could be placed somewhere easier to find though..

**Comment by gmansillo** [comment]
Hi @IrmaBe,
please help improving the component: suggest me a better place where to put this setting in order to make it easier to find!

Thanks,
Giovanni
