### ISSUE TITLE
Utenti che Caricano Documenti

### ISSUE THREAD

**Issue by nesple** [gmansillo/simple#79]
È possibile avere delle schermate di upload dedicate per ogni singolo utente, in modo che egli possa caricare file associati a lui stesso?

**Comment by gmansillo** [comment]
Ciao @nesple ,
prova a creare una voce di menu di tipo "Documenti" (o "Simple", in base alla versione che usi) -> Invia documento.

**Comment by nesple** [comment]
Ciao @gmansillo,
ti ringrazio per la celere risposta, avevo già fatto questa prova, provo a spiegarmi meglio:

1. Ho creato la voce di menù
2. Ho abilitato la visione della pagina anche agli utenti registrati (non solo al Super User) tramite "Opzioni -> Simple -> Permessi"
3. Vado nella schermata di Caricamento file dove gli upload funzionano benissimo
4. Riscontro il problema che utente "Pino" può associare il file che carica a tutti gli altri utenti "Gianni, Alessandro, Ecc"

C'è la possibilità di permettere al singolo utente di associare il file caricato in automatico a se stesso?

Il sito che sto andando a costruire prevede un upload di file divisi per utenti (lato Back-end) da parte degli amministratori. Gli utenti con una login pregenerata (lato Front-End) vedono solo i file a loro stessi associati, ma devono avere la possibilità  di caricare (lato Front-End) file da associare al loro elenco di documenti, senza chiaramente vede l'elenco degli altri utenti.

Grazie mille per la disponibilità e per il componente che è davvero ben fatto!

**Comment by gmansillo** [comment]
Ok, ora mi è chiaro il problema.
Per caso hai dato a registred il permesso di gestione (quello tipico dei manager)? 

Prova a dargli solo il permesso di creazione:
![smartselectimage_2017-10-05-19-18-51](https://user-images.githubusercontent.com/11967003/31240847-49afbd72-aa02-11e7-80b9-bac797a59cc2.png)

**Comment by nesple** [comment]
Ciao Giovanni, si ho provato a impostare come dici tu e il risultato è quasi buono.
Ti spiego cosa manca allegando un immagine:
Nel primo e nel secondo riquadro vedi la pagina di caricamento create nella quale l'ipotetico utente Alessandro può caricare file anche abbinandoli a tutte le categorie degli altri utenti, c'è un modo per far comparire soltanto la sua?
Nel terzo riquadro puoi vedere il file caricato che risulta non pubblicato, che quindi come puoi vedere nel quarto riquadro non si vede nella sua sezione documenti front-end. 
![aaa](https://user-images.githubusercontent.com/32514875/31267014-c5945f46-aa76-11e7-8e57-342be27d2e5e.jpg)

Il file si carica sospeso perché l'interfaccia amministrativa nei permessi di gestione è disattivata, quindi Joomla di default lo carica sospeso, ma questo penso sia facilmente ovviabile come problema, basta dare un comando che renda di default pubblicati i file che vengono caricati.

Per la problematica della selezione della categoria una possibile soluzione potrebbe essere implementare il campo "Visibilità Utenti" presente per gli articoli anche per le categorie.

Ps. ho fatto anche alcune prove con "Accesso interfaccia amministrativa" impostata su Consentita, ma a quel punto le possibilità della pagina di upload aumentano, quindi eviterei di analizzare il caso.

**Comment by gmansillo** [comment]
Credo che il fraintendimento nasca dal diverso uso che farei io di una categoria. Ad esempio, io non avrei creato una categoria "_Documenti di...._" ma solo "_Miei documenti_" ed all'interno lascerei ogni utente caricare i file con la visibilità corretta (solo autore, tutti gli utenti, utenti selezionati, ecc..., in base ai privilegi che ha). Inoltre potrei, in questo modo, aggiungere una opzione _visibilità di default_ per gli utenti che non possono selezionare una visibilità perché non hanno i permessi.

Alla fine ogni utente pubblicherà nella stessa categoria, ma potrà vedere solo i documenti che hanno una visibilità tale da consentirgli l'accesso.

Una nota: non sto ragionando sulle categorie solo perché quelle sono gestite direttamente da Joomla e prevedono ACL a livello di ruolo/gruppo e non di utente!

**Comment by gmansillo** [comment]
Per quanto riguarda il problema della pubblicazione mi sembra ( 💡 ) che basti dare all'utente il privilegio di "cambio stato"

**Comment by nesple** [comment]
Ho provato a spostare il problema alle categorie perché le prove svolte in altro senso non trovavano soluzione al mio problema, concordo con te che il loro utilizzo in questo modo è errato.

Se si riuscisse ad impostare agli utenti che caricano senza i permessi di amministrazione, quindi non avendo possibilità di impostare la _visibilità_, l'associazione automatica a _solo autore_ sarebbe il top.

Ho provato a dare agli utenti la capacità di cambio stato ma i tasti sono disabiliti, come vedi dallo screen, anche qui si può impostare che gli utenti senza privilegi di cambio stato carichino i file già pubblicati magari.

![schermata 2017-10-06 alle 10 39 57](https://user-images.githubusercontent.com/32514875/31269957-bbeeb200-aa82-11e7-978e-ccf4e0e28055.png)

Ps. La modifica ad unica categoria l'ho già apportata, è sicuramente il modo giusto di pensare a categoria!

**Comment by gmansillo** [comment]
Ciao,
ho provato ad apportare le modifiche richieste ed ho corretto altri errori. Puoi darmi un feedback?
[com_simplefilemanager-5.1.3.zip](https://github.com/gmansillo/simple/files/1368876/com_simplefilemanager-5.1.3.zip)

Successivamente lo renderò disponibile anche come aggiornamento automatico.

PS: Mi raccomando, backup del db prima di aggiornare!

**Comment by nesple** [comment]
Buongiorno Giovanni,
con questo aggiornamento mi risultano un p'ò di problemi. La Nota positiva è che i documenti vengono caricati come Pubblicati.

Cosa c'è che non va:

1. La Visibilità Utente è completamente saltata, se io imposto che solo l'utente Alessandro possa vedere il file, se entro con l'utente Giovanni lo vede e lo scarica. (Utenti allo stesso livello Registered).
2. Per quanto riguarda l'upload di documenti dal front-end è migliorato rispetto a prima ma comunque il documento caricato risulta "Visibile a tutti i Public" invece che hai "Registered", ma sopratutto non viene associata la visibilità all'utente che lo carica.

Ti metto a disposizione il Joomla su cui sto facendo queste prove cosi che possiamo lavorarci insieme. http://cambioauto85.com/caricamento/administrator

Gli utenti presenti sono 3 (ti lascio le login e le password):
Super Users: admin admin
Registered: alessandro alessandro
Registered: giovanni giovanni

Ciao Alessandro

**Comment by gmansillo** [comment]
Ciao Alessandro,
grazie per la tua disponibilità. Ho effettuato l'accesso al tuo sito ed ho notato queste cose: 

- Riguardo al primo punto: ho notato che il documento che hai riservato ad Alessandro in realtà ha visibilità "Utenti registrati" e non "Utenti selezionati". Avevi già impostato questo valore?
- Per quanto riguarda il caricamento da frontend effettivamente ho fatto degli errori: ho dimenticato di inserire il campo visibilità prefefinita nelle opzioni globali ed ho invece inserito lo "stato predefinito" che dovrebbe essere published solo se l'utente ha i privlegi di cambio stato.

Correggo quantoprima e carico il pacchetto aggiornato

**Comment by gmansillo** [comment]
Ho aggiunto anche l'impostazione globale "Visibilità di default". Ora è possibile selezionare i valori di default di **visibilità** e **stato** per gli utenti che non hanno i privilegi di cambiarli nel frontend.

Spero che sia tutto in ordine, così posso procedere con il rilascio dell'aggiornamento:
[com_simplefilemanager-5.1.3-rev1.zip](https://github.com/gmansillo/simple/files/1374479/com_simplefilemanager-5.1.3-rev1.zip)

**Comment by nesple** [comment]
Ciao Giovanni, 
credi che ci siamo quasi, la visualizzazione solo autore funziona!
L'unico problemino è che nonostante ci sia impostato come stato predefinito publico il file viene caricato sospeso...

**Comment by gmansillo** [comment]
Niente paura, ho cambiato lo stato di default a "sospeso" ed evidentemente - poiché il numero di versione di Simple è rimasto lo stesso rispetto al precedentemente pacchetto - Joomla! non ha recepito la modifica. Prova a cambiare questo settaggio dalle impostazioni globali (eventualmente più di una volta) e fammi sapere!

Grazie

**Comment by nesple** [comment]
Ho fatto delle prove, ti dico alcune supposizioni:
Con la versione 5.1.3 l'utente semplice (con "modifica stato --> negata") caricava il file e questo veniva caricato pubblico. 

Con la versione 5.1.3-rev1  l'utente semplice (con "modifica stato --> negata") carica il file e questo veniva caricato sospeso. Nonostante si imposti come stato predefinito pubblicato, archiviato o cestinato.

Il problema potrebbe essere che avendo l'utente la "modifica stato --> negata" e il componente di default da la visibilità sospesa, durante il caricamento Joomla non riesce a cambiare lo stato del file.

Se invece diamo la "modifica stato --> consentita" l'utente in fase di caricamento può scegliere lo stato del documento, però è superfluo dargli questa possibilità secondo me. Sopratutto perché in questo modo vede i documenti che il super user può aver caricato per lui ma che ancora non ha pubblicato.

Ps. ti lascio il sito con "modifica stato --> consentita" e "stato predefinito --> pubblico"

**Comment by gmansillo** [comment]
Ottima intuizione Alessandro!
Nel model c'era un vecchio frammento di codice (di cui neanche ricordavo l'esistenza) che forzava a 0 lo stato se l'utente non aveva i permessi. Ora dovrebbe essere tutto ok.

Spero che questa sia la volta buona 😄 

[com_simplefilemanager-5.1.3-rev2.zip](https://github.com/gmansillo/simple/files/1376324/com_simplefilemanager-5.1.3-rev2.zip)

**Comment by nesple** [comment]
Ciao Giovanni,
mi dispiace ma nada, li carica ancora come sospesi =(
Per paura che dipendesse dall'aggiornamento del componente, ho fatto una nuova install di Joomla e ricreato tutto da zero, ma niente.

Nella versione 5.1.3 senza rev questa funzione va alla grande, quindi le possibilità sono due:
1. In quella versione lo stato di default del documento era pubblicato, quindi va impostato su pubblicato.
2. Inserendo sotto la "scelta dello stato predefinito" la "visibilità predefinita" può essere saltato qualcosa.

**Comment by gmansillo** [comment]
Dai che possiamo farcela: [com_simplefilemanager-5.1.3-rev3.zip](https://github.com/gmansillo/simple/files/1382159/com_simplefilemanager-5.1.3-rev3.zip)

**Comment by nesple** [comment]
Yessssssssssss!!! Funziona tutto alla perfezione!
Grazie mille di tutto e complimenti per l'ottima estensione!

**Comment by nesple** [comment]
Yessssssssssss!!! Funziona tutto alla perfezione!
Grazie mille di tutto e complimenti per l'ottima estensione!

**Comment by nesple** [comment]
Yessssssssssss!!! Funziona tutto alla perfezione!
Grazie mille di tutto e complimenti per l'ottima estensione!

Ps. lascio a te la chiusura!

**Comment by gmansillo** [comment]
Grazie a te per il supporto 😉
