### ISSUE TITLE
Aggiornamento e sicurezza

### ISSUE THREAD

**Issue by pulici11** [gmansillo/simple#80]
Due domande immagino sciocche per cui mi scuso.
Per effettuare l'aggiornamento del componente su joomla devo scaricare lo zip clone or download dal repository?
Una volta fatto in questo modo, i file non erano più scaricabili, oltre ad avere le etichette con il prefisso con nel lato back, come posso ovviare?
Infine i file caricati se si ha l'url sono scaricabili anche senza credenziali, esiste un metodo per permettere lo scaricamento solo a utenti registrati?

Grazie e scusate

**Comment by gmansillo** [comment]
Ciao @pulici11,
per scaricare l'ultima versione di Simple usa il link in questa pagina: http://gmansillo.github.io/simple/
La versione attualmente su github non è aggiornata per via di problemi di sincronizzazione con subversion che sto ancora  risolvendo.

Se selezioni la visibilità "utenti registrati" per un file, non dovrebbe essere possibile scaricarlo senza autenticazione. Se così non fosse, si tratta chiaramente di un bug che va corretto. 

Un caro saluto,
Giovanni

**Comment by pulici11** [comment]
Grazie mille, ti faccio sapere nei prossimi giorni, intendi caricare il file php?

**Comment by gmansillo** [comment]
Devi scaricare e caricare in joomla l'intero pacchetto scaricato come descritto [qui](https://github.com/gmansillo/simple/wiki) sotto la voce "Installation".
