### ISSUE TITLE
Problema con accesso ai documenti e gruppi

### ISSUE THREAD

**Issue by mrsw** [gmansillo/simple#81]
Ciao Giovanni,
ho scaricato ed installato l'ultima versione del componente, dopo aver eliminato il back link con donazione).
La vecchia versione, funzionava correttamente, ora ho problemi.
Ho rimosso il vecchio componente prima di installare la versione aggiornata ed ho perso i dati che avevo inserito.
Ho reinserito documenti e categorie, ma ora quando seleziono Accesso -> "Gruppi Selezionati" per un documento e seleziono i gruppi che possono accedere a quel documento (gli stessi che erano impostati prima di installare al nuova versione), gli utenti di quel gruppo non vedono il documento. Ho notato che aggiungendo nell'elenco dei gruppi abilitati anche il gruppo "Registered" vedo il documento. La stessa cosa accade se seleziono Accesso -> "Utenti registrati".
Hai qualche idea su quale possa essere il problema? Funzionava male la versione precedente, quindi ho sbagliato io qualche cosa con i gruppi, oppure è un problema della nuova?
Grazie.

    Carlo Marona

**Comment by gmansillo** [comment]
Ciao Carlo, 
grazie per la segnalazione! Effettivamente c’è un bug nel sistema. Verificherò dove risiede l’errore e provvederò quanto prima a rilasciare una patch di aggiornamento.

**Comment by mrsw** [comment]
Ciao Giovanni,
ho dato un'occhiata la codice e credo di aver risolto il problema.
In allegato trovi i fali che ho modificato. Verifica, nel mio caso sembra funzionare.
Ciao.

    Carlo Marona

Il 10/11/2017 21:50, Giovanni ha scritto:
Ciao Carlo,
grazie per la segnalazione! Effettivamente c’è un bug nel sistema. Verificherò dove risiede l’errore e provvederò quanto prima a rilasciare una patch di aggiornamento.

**Comment by gmansillo** [comment]
Ciao Carlo, sfortunatamente non ho ricevuto l'allegato.
Nel frattempo mi sono accorto che online non era ancora ufficialmente scaricabile la 5.1.3 che contiene alcune correzioni ai bug precedenti. Verificherò appena possibile che il bug non sia presente anche in questa.

Ciao e grazie ancora per la tua segnalazione ed il tuo supporto

**Comment by mrsw** [comment]
Ciao Giovanni, spero questa volta l'allegato arrivi.
Contiene:
- Correzione problema con i gruppi che ti avevo segnalato
- Correzione icona documenti .pdf (aveva uno sbaffo in alto a sinistra
- Correzione visualizzazione icona documento in dettagli documento (ora visualizza la stessa icona dell'elenco documenti)
Non so cosa usi, ma con winmerge puoi vedere le differenze tra le mie modifiche ed il codice originale.

[Simple File Manager.zip](https://github.com/gmansillo/simple/files/1535511/Simple.File.Manager.zip)
