### ISSUE TITLE
installazione backlink free version non funziona

### ISSUE THREAD

**Issue by gianlusat** [gmansillo/simple#82]
Ciao Giovanni, dopo avere testato l'estensione ho fatto la donazione per ricevere la versione senza backlink. com_simplefilemanager-5.1.2p
Purtroppo dopo l'installazione, nonostante mi viene mostrato il messaggio di corretta installazione, scopro che il componente non è più presente, nemmeno la precedente versione. Ho perso tutto?
il mio joomla è 3.7.5
Puoi aiutarmi? Grazie

**Comment by gmansillo** [comment]
Assolutamente no! :) 
Puoi trovare Simple sotto Estensioni -> Documenti, in analogia agli altri componenti integrati in Joomla come  banner, contatti, ecc.

Spero di esserti stato d'aiuto.

Un saluto,
G.

**Comment by gianlusat** [comment]
![simple-issue](https://user-images.githubusercontent.com/25224000/33146883-3b99fd12-cfc6-11e7-8ecf-b7652111e984.png)

purtroppo non ancora : )
credo di avere un problema perchè non è presente nella lista components, dove dovrebbe stare. vedi screenshot

**Comment by gianlusat** [comment]
in aggiunta se vado su extension>update trovo questi warnings:
Update: :Extension: Could not parse --------
Update: :Extension: Could not parse -------- 

_edit: ho nascosto le url di aggiornamento non valide per non generare confusione e tutelare chi, come te, ha fatto una donazione_

**Comment by gmansillo** [comment]
Il link per accedere al componente si trova proprio qui:
![immagine](https://user-images.githubusercontent.com/11967003/33654346-143d06ba-da70-11e7-8a92-1ea7a65cc384.png)

Effettivamente le url di aggionamento puntavano a pagine inesistenti. Ho inserito un redirect a quelle corrette, ora tutto dovrebbe funzionare!

Grazie per la segnalazione
