### ISSUE TITLE
Sort function not working

### ISSUE THREAD

**Issue by ghost** [gmansillo/simple#83]
I've successfully set up the document manager on Joomla 3. However, none of the sorting functions on the front-end actually work (Date created, Title, Ordering, Ascending, Descending).

When you click on them - the page reloads but the results are still the same.

http://acertis.services/index.php/resource-center?view=simplefilemanagers&catid=20

**Comment by lsavino59** [comment]
Anch'io riscontro lo stesso problema.
La versione precedente funzionava, aggiornando alla nuova non funziona più nessun tipo di ordinamento, sia nel backoffice che nel front-end.

**Comment by gmansillo** [comment]
Than you both for your feedback. I'm going to fix that issue as soon as possible.

**Comment by ghost** [comment]
Any progress on this? Really need it for a client.

**Comment by gmansillo** [comment]
I wasn't able to find the real cause of the issue you reported but I had to rewrite from scratch all the project since I found some other bugs and incompatibility with Joomla! 3.8 😦 .
I'm currently working on it. Backend side is almost completed. I'm going to work on the frontend side.
Sorry for the inconvenience, I'll keep you updated!

**Comment by ghost** [comment]
That's a shame. I'll have to use another plugin for now. Keep me posted when you launch the updated version.

**Comment by gmansillo** [comment]
Hi @lsavino59, @f4dmediadev,
I have just finished to add sorting function in frontend. I can confirm that it works well. Soon you will find online the installation package of the working version (5.1.4). You can yet find the working source code on github.

Thank you both for your support.
G.
