### ISSUE TITLE
Problemi riscontrati

### ISSUE THREAD

**Issue by leoenrik** [gmansillo/simple#84]
Ciao Giovanni innanzitutto complimenti per il tuo lavoro...

Volevo però portarti all'attenzione due problemi riscontrati....  Ho Joomla! 3.8.2 Stable

1) Se scarico dal tuo link com_simplefilemanager-5.1.3 e provo ad installarlo mi dice operazione completata ma non viene visualizzato nel menu componenti....
2) Se invece faccio il download da qui (simple-master.zip) ed installo lo trovo ma se entro in Gestione Documenti mi da questo errore: 500 Unknown column 'a.file_created' in 'field list'

Grazie Enrico

**Comment by gmansillo** [comment]
Ciao Enrico,
grazie per il tuo feedback. Puoi trovare il componente sotto Estensioni->Documenti (sto inserendo delle note più esplicative in questo senso da mostrare all'atto dell'installazione). 

Ti prego di non considerare il codice attualmente su github perchè per problemi di sincronizzazione con svn non è aggiornato alla versione più recente.

Un saluto,
Giovanni

**Comment by leoenrik** [comment]
Ciao Giovanni scusami ma non ho capito bene dove trovare il componente... Estensioni->Documenti qui su github o altrove?!?!? Perchè quello collegato alle estensioni di joomla mi da l'errore 1 mi dice installato ma non si visualizza niente!

Grazie Enrico

**Comment by gmansillo** [comment]
Ho fatto un errore di percorso, è sotto Componenti e non Estensioni come detto in precedenza:

![image](https://user-images.githubusercontent.com/11967003/35144920-4962300a-fd06-11e7-96fe-eb5a4c46af28.png)
