### ISSUE TITLE
Ordinamento di default

### ISSUE THREAD

**Issue by fabryz71** [gmansillo/simple#86]
Complimenti per il tuo lavoro Giovanni.
C'è un modo per impostare che l'ordinamento di default dell'elenco dei file venga per "ordinamento" ? senza quindi doverlo scegliere dalla select ?

Al limite anche con un override in attesa della features se nn c'è e la vorrai mettere ...

Grazie

**Comment by gmansillo** [comment]
Ciao @fabryz71,
purtroppo non è possibile lavorare sulla query che popola le liste tramite una override.
Per alcuni problemi che si sono accumulati nel tempo, sto riscrivendo completamente l'estensione: appena passerò al frontend, terrò conto del tuo suggerimento. 

Grazie

**Comment by gmansillo** [comment]
Sto provvedendo ad inserire tale funzionalità nelle impostazioni del backend. Troverai la modifica nella versione 5.1.4.

Grazie ancora per il suggerimento!
