### ISSUE TITLE
Aggiornamento Simple file Manager dalla 5.0.12 alla 5.1.3

### ISSUE THREAD

**Issue by mfelice1976** [gmansillo/simple#87]
Buongiorno @gmansillo ,
mi sono accorto che stranamente joomla (ora alla vers. 3.8.5) non mi segnala più che esiste una nuova versione e che devo fare l'aggiornamento. Precedentemente mi diceva che dovevo aggiornare alla 5.1.2 credo ma dopo l'aggiornamento la release restava sempre allla 5.0.12 e mi riproponeva di aggiornare, poi non ho avuto più notifiche. Se forzo joomla a cercare aggiornamenti mi dice che è tutto aggiornato. Come posso risolvere il problema? Premetto che sul sito gestisco 1500 utenti e che per ogni utente ci sono caricati diversi file suddivisi già per categoria ed ho un pò paura di perdere il lavoro fatto negli ultimi 3 anni.
Se carico ed installo l'ultima versione si aggiorna automaticamente o devo prima disinstallare la vecchia?
Ringrazio anticipatamente per la cortese collaborazione.

**Comment by gmansillo** [comment]
Ciao @mfelice1976 ,
sono felice che stai utilizzando Silmple in modo così efficace. Devo avvisarti, tuttavia, che le ultime versioni portano con sè degli errori (anche relativi alla procedura di aggiornamento) che ad oggi non sono stato in grado di risolvere. Per tale motivo ho dovuto rimuovere l'aggiornamento automatico per la versione attualmente in uso (5.0.12). Questa, tuttavia, non presenta problemi di sicurezza e può tranquillamente essere utilizzata se le funzionalità presenti sono sufficienti allo scopo.
Qualora invece volessi aggiornare comunque all'ultima versione, ti consiglio di attendere il prossimo aggiornamento (5.1.4), versione che sto riscrivendo da 0 e per la quale rilascerò un'apposita guida per la procedura di aggiornamento.

Spero che queste indicazioni ti siano utili.
Un saluto,
Giovanni

**Comment by gmansillo** [comment]
La 5.1.4 è ora disponibile. Appena possibile rilascerò anche una guida per migrare dalle versioni precedenti alla 5.1.4.
L'aggiornamento automatico non è possibile!

**Comment by mfelice1976** [comment]
Grazie @gmansillo, vorrei condividere con te il codice php che utilizzo per il popolamento massivo.
premesso che i miei utenti si collegano con user= codice fiscale, dopo aver fatto l'upload della cartella via ftp sul server ( il name file è = a codicefiscaleutentenomefile) richiamo una pagina html dove inserisco i parametri di connessione, poi richiama il codice php che segue:
<?php
 
$host = $_POST['host'];     //nome host
$username = $_POST['username'];      //user name
$password = $_POST['password'];  //password
$db = $_POST['database'];            // nome data base
//---connessione----------------------------------------------------
$conn = @mysqli_connect($host,$username,$password) or die ("impossibile connettersi al server");

$sel = @mysqli_select_db($conn,$db) or die ("impossibile connettersi al db");

$inserted_rec=0;

    $data=date('d/m/Y');
    echo "<p>";
    echo "Inserimento record eseguito in data $data ";
    echo "</p>";
    
//scorro i files pdf della cartella "NomeCartella", controllo se esiste un record corrispondente (tramite codice fiscale)
//nella tabella jos_users. Se il record esiste inserisco un corrispondente record nella tabella jos_simplefilemanager
//$dir = '../NomeCartella/';
$dir=$_POST['percorso'] . '/';  
    
// estraggo i file
$f = glob($dir.'*.pdf');
               
// faccio un ciclo all'interno del vettore $f contenente l'elenco dei files
foreach ($f as $filepath)
{
  // la funzione glob restituisce il nome del file comprensivo di directory.
  // Uso quindi la funzione basename per estrarre il nome del file con o senza estensione 
  
  $file = basename($filepath);
  $file_noext = basename($filepath, ".pdf");
  //verifica che nella tabella jos_simplefilemanager non sia già presente un record relativo al documento
  $query_check="SELECT id FROM jos_simplefilemanager WHERE title = '$file' ";
    
  $rs_check=mysqli_query($conn,$query_check);
  
  $num_rows_check=mysqli_num_rows($rs_check);
    
  if($num_rows_check==0) //se il record relativo al documento non esiste allora lo inserisco
  { 
  //query sulla tabella jos_users con criterio di selezione costituito dal codice fiscale
  //ricavato dai primi sedici caratteri della variabile $file
  
  $username=substr($file, 0, 16);
  
  $query_stringa="SELECT * FROM jos_users WHERE username = '$username' ";
 
  $query=mysqli_query($conn,$query_stringa) or die ("impossibile eseguire query"); //query
              
  $num_rows=mysqli_num_rows($query); //numero di record presenti se == 0 si salta il ciclo
                
  if($num_rows>0)
   {
  
      $row = mysqli_fetch_array($query);
               
      $idUtente=$row['id'];
      $data=date('Y/m/d H:i:s');
      
      $sql_insert = "INSERT INTO jos_simplefilemanager (id, title, catid, state, file_name, visibility, reserved_user, reserved_group, file_created) 
      VALUES (NULL, '$file', '30', '1', '$filepath', '3', '$idUtente', '1', '$data')";
      mysqli_query($conn,$sql_insert) or die ("impossibile eseguire query di inserimento");
      
      echo "<p>";
      echo $file;
      echo "</p>";
    
      $inserted_rec=$inserted_rec+1;
  }
  }
}

mysqli_close($conn);
    
    echo "<p>";
    echo "Inseriti $inserted_rec records";
    echo "</p>";

?>
