### ISSUE TITLE
Listing all category, not just one

### ISSUE THREAD

**Issue by mrbean2** [gmansillo/simple#89]
Hi!

I need help with Simple.
I have the categories created. Uploaded, and assigned files to them.

I tried to add a new menu item to the menu bar. Using 'menu item type' i found 'documents' which belongs to Simple i presume.
But it force me to choose only one category, not to list all of them.

To make it short:
how can I list all created category on a page?

**Comment by gmansillo** [comment]
Hi @mrbean2,
I introduced this possibility in version 5.1.4. It'll be available soon.
Alternatively, you can create a parent category linking it in menu.

**Comment by gmansillo** [comment]
5.1.4 is now availble. NB: you can't directly upgrade from 5.1.3 to 5.1.4 but I'll publish a tutorial for manual upgrade as soon as I can.

Best regards
