### ISSUE TITLE
Bogue version 5.1.4

### ISSUE THREAD

**Issue by Techal62** [gmansillo/simple#90]
Hello, I installed version 5.1.4 on Joomla 3.8.5 and I encounter problems.

1st problem: When creating a document I have an error message, Invalid field creation date, invalid field modification date

2nd problem: I want to create a page that displays the documents of a category, I can not choose the category because it shows me Error invalidation failed with the following error: no error code nothing displayed

I have screenshots if it helps

Thank you

**Comment by gmansillo** [comment]
Hi, I just created a document in Joomla! 3.8.6 with default parameters but i didn't get those errors. Can you help me reproducing the issue? 

I went in Menu > Main menu > Add new menut item, then i created a Simple File Manager > "List All Document Categories" menu item. When I pressed the green save button I didn't get any error message. Can you help me reproducing also this issue?

Thank you in advance for your time and your patience

**Comment by gmansillo** [comment]
Hi @Techal62, please let me know!  :pray:

**Comment by Techal62** [comment]
Hello,

I'm testing again this week and I'll keep you informed.

Is it possible to integrate a search module on your plugin?

 

De : Giovanni Mansillo [mailto:notifications@github.com] 
Envoyé : jeudi 29 mars 2018 23:47
À : gmansillo/simple
Cc : Techal62; Mention
Objet : Re: [gmansillo/simple] Bogue version 5.1.4 (#90)

 

Hi @Techal62 <https://github.com/Techal62> , please let me know! 🙏

**Comment by gmansillo** [comment]
Yes, is it possibile following this tutorial: https://docs.joomla.org/J3.x:Creating_a_search_plugin

Currently exists only an intenal filter for each category.

**Comment by Techal62** [comment]
Thank you very much I retest your plugin and I keep you informed.

thanks again

 

De : Giovanni Mansillo [mailto:notifications@github.com] 
Envoyé : vendredi 30 mars 2018 07:51
À : gmansillo/simple
Cc : Techal62; Mention
Objet : Re: [gmansillo/simple] Bogue version 5.1.4 (#90)

 

Yes, is it possibile following this tutorial: https://docs.joomla.org/J3.x:Creating_a_search_plugin

Currently exists only an intenal filter for each category.

**Comment by Techal62** [comment]
I tested version 5.1.4 under a new installation of Joomla, everything went well, I think my initial base joomla to problems.

Thanks again

 

De : Giovanni Mansillo [mailto:notifications@github.com] 
Envoyé : vendredi 30 mars 2018 07:51
À : gmansillo/simple
Cc : Techal62; Mention
Objet : Re: [gmansillo/simple] Bogue version 5.1.4 (#90)

 

Yes, is it possibile following this tutorial: https://docs.joomla.org/J3.x:Creating_a_search_plugin

Currently exists only an intenal filter for each category.

**Comment by gmansillo** [comment]
Thank you for your feedback!
