### ISSUE TITLE
 Class 'SimplefilemanagerHelper' not found 

### ISSUE THREAD

**Issue by gooseclam** [gmansillo/simple#91]
Installed 5.1.4 on Joomla 3.8.6 PHP 7.028.
I can create a new category but when I go to documents I get an inactive screen with the message:

> An error has occurred.

    0 Class 'SimplefilemanagerHelper' not found

**Comment by gmansillo** [comment]
Hi @gooseclam, do you get this error in front or backend?

**Comment by gooseclam** [comment]
In the backend: Components->Simple File Manager->Documents. Categories seems to work. This is a new installation which I have also uninstalled and reinstalled.

**Comment by gmansillo** [comment]
Thank you for your feedback. Unfortunately i'm unable to reproduce the issue since all seems to work fine on my local and remote installations. Can you help me reproducing it in some way? 
Is it possible that you had a previous version of simple file manager installed before installing the new one?

**Comment by gooseclam** [comment]
This is a brand new installation. I have uninstalled and reinstalled in attempt to get it working.
If I look at your YouTube video (I don't speak Italian) Then I fail at the step at 1:06.
When I turn on debug this is the call stack:
`

Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_simplefilemanager/views/documents/view.html.php:63
2 | SimplefilemanagerViewDocuments->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
3 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_simplefilemanager/controller.php:40
4 | SimpleFileManagerController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_simplefilemanager/simplefilemanager.php:17
6 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:382
7 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:357
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
9 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
10 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:204
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:

`

**Comment by gmansillo** [comment]
Is there a file called simplefilemanager.php in administrator/components/com_simplefilemanager/helpers/ ?

**Comment by gooseclam** [comment]
Yes there is.

**Comment by gmansillo** [comment]
I can't figure out where is the error. It's like your Joomla engine isn't auto-loading the helper class. As you can see in this screenshot, all seems to work correctly: 
![2018-03-28-103641_1366x768_scrot](https://user-images.githubusercontent.com/11967003/38023453-a574147e-3282-11e8-9bd8-279135a0b6e8.png)

I think the cause should be found elsewhere :disappointed: 
Is there any other third-part extension installed?
Is it a brand new installation of Joomla! too?

**Comment by gooseclam** [comment]
Firstly thanks for your quick responses.
It is installation that goes back to Joomla 2.4 with regular upgrades.
Yes many other components installed - The usual Akeeba etc etc and JEM event manager.
Is there anything I can do to investigate this further?
I assume Categories create a directories. If so where are they?

**Comment by gmansillo** [comment]
I really don't know how to solve the issue. I could think that some past updates went wrong and you never noticed the issue before installing Simple File Manager. I can suggest you to add an import directive for:

> administrator/components/com_simplefilemanager/helpers/simplefilemanager.php

but you'll lost this directive at the first component update. 

Categories are an abstract concept and don't correspond to a phisical path: they are stored in the "categories" table of your database.

**Comment by gooseclam** [comment]
OK I'll think about it tomorrow.

**Comment by gmansillo** [comment]
Hi @gooseclam ,
did the include directive solve the issue?
