### ISSUE TITLE
File cache problem by users

### ISSUE THREAD

**Issue by Techal62** [gmansillo/simple#93]
Hello, I encounter a problem of cache, with documents by users.
I create a category in which I put documents accessible by user.
When the Joomla cache is activated, if I connect with a user and log out, when I connect with another user, the files that appear are those of the first user. If I disable the Joomla cache I see the files of the right user?

**Comment by gmansillo** [comment]
Hi @Techal62,
thank you for reporting this issue. Wich version of Simple file manager are you using?

**Comment by Techal62** [comment]
Hello, my version is 5.1.4

**Comment by gmansillo** [comment]
Please try to remove the following lines from components/com_simplefilemanager/controller.php:
```
        if (JFactory::getApplication()->getUserState('com_simplefilemanager.document.data') === null) {
            $cachable = true;
        }
```
Then purge browser and Joomla! caches and retry

**Comment by Techal62** [comment]
Thank you very much, this solved the problem.

**Comment by gmansillo** [comment]
This fix will be included in next release.
Thank you for reporting the issue.
