### ISSUE TITLE
Wrong path after server migration

### ISSUE THREAD

**Issue by SamoCafnik** [gmansillo/simple#96]
Hi there, we migrated servers a couple of days ago and noticed, that the old download links aren't working. I figured out that the file path still points to the old site. For instance instead of /home/naju01/domains/sidg.si/public_html/administrator/components/com_simplefilemanager/ as it did before it should now point to /home/unistar/public_html/sidg.si/administrator/components/com_simplefilemanager/uploads/.

Is there a way to fix that within the system?

**Comment by gmansillo** [comment]
Of course.
You have to execute an update query on your database, like the following one:

```
UPDATE #__simplefilemanager
SET file_name = REPLACE(file_name, '/home/naju01/domains/sidg.si/public_html/', '/home/unistar/public_html/sidg.si/')
```

Nb: replace #_ with the right table prefix and check the right format of your paths because tin the old one is missing the final 'uploads' folder

**Comment by gmansillo** [comment]
Hi @SamoCafnik ,
please let me know if the posted solution was useful for you!

**Comment by SamoCafnik** [comment]
Hi, sorry, was away on vacation. Yes, it helped, everything works fine. Thank you very much!

**Comment by gmansillo** [comment]
Thank you for your feedback! :-)
