### ISSUE TITLE
Problemi di installzione con Joomla 3.8.6

### ISSUE THREAD

**Issue by salvocc** [gmansillo/simple#98]
Ciao,
ovviamente mi associo con tutti colore che ti hanno fatto i complimenti per il gran bel lavoro fatto con questo componente, vengo alla questione in oggetto .
Durante la fase di installazione il componente la procedura non va a buon fine con il seguente errore .

JInstaller: :Install: Non è stato possibile trovare il file di setup XML
JInstaller: :Install: Errore SQL Table 'cmeddb.#__simplefilemanager' doesn't exist
Estensione Aggiorna: richiesta di elaborazione degli errori di SQL: DB function fallita con errore numero 1146
Table 'cmeddb.#__simplefilemanager' doesn't exist
SQL =

INSERT IGNORE INTO `#__simplefilemanager_user_documents` (user_id, document_id)
  SELECT
    reserved_user,
    id
  FROM `#__simplefilemanager`
  WHERE reserved_user != NULL;

La versione di joomla è 3.8.6
Versione PHP: 7.1.11 
Tipo di server: MariaDB 

Grazie anticipatamente.

**Comment by gmansillo** [comment]
Ciao Salvo,
sono infinitamente dispiaciuto di non aver risposto prima al tuo quesito, spero di potermi far perdonare in qualche modo.
Sembra che il sistema riconosca che una vecchia versione di Simple File Manager sia stata installata sul sistema ma che le sue tabelle non siano più disponibili. Ti risulta?
