### ISSUE TITLE
Errore data al salvataggio

### ISSUE THREAD

**Issue by ilFedera** [gmansillo/simple#99]
Ciao
e complimenti per il lavoro!

Riscontro che al salvataggio di ogni doc il sistema mi riporta 
_Campo non valido: Created Date
Campo non valido: Data modifica_

Se modifico ... mi riporta solo "_Campo non valido: Data modifica_"

e inoltre il box per l'invio all'utente della mail generata appare solo dopo aver salvato il documento.

Per concludere vorrei sapere se è possibile spostare la cartella di destinazione dei documenti caricati sotto "images"

Grazie infinite! ;-)

**Comment by gmansillo** [comment]
Ciao @ilFedera ! 
Accetto con tanta gratitudine i tuoi complimenti e ti ringrazio per la segnalazione: verificherò al più presto il problema del campo non valido.

L'invio dell'email al primo salvataggio è gestibile dalle opzioni globali del componente: se questa opzione è attiva, al primo salvataggio l'utente riceverà l'email mentre per i successivi salvataggi è necessario spuntare la casellina, che già conosci :smiley:  

Purtroppo non è possibile cambiare la cartella in cui sono salvati i documenti caricati ma ti sconsiglio di salvare i file nella cartella images in quanto potrebbero entrare in conflitto con il media manager di joomla.

**Comment by gmansillo** [comment]
Ciao,
non riesco a replicare l'errore della data al salvataggio, probabilmente non me ne sono accorto ed è stato già risolto negli ultimi aggiornamenti. Qualora dovessi riscontrare il problema anche con le ultime versioni non esitare a riaprire la discussione :wink: 

Un saluto,
G.

**Comment by gmansillo** [comment]
L'errore continua a presentarsi sulla 5.2.5 ( issue #131 )
